'use client'

/**
 * ============================================================================
 * PDF Forge — HTML to PDF Tool
 * ----------------------------------------------------------------------------
 * Genuine browser-rendered PDF via server-side Chromium (@sparticuz/chromium).
 * NOT html2canvas→image→jsPDF. Real print CSS, real fonts, real vector text.
 *
 * Privacy: HTML is sent to server for rendering. PDF returned immediately.
 * No URL→PDF mode (SSRF risk deferred).
 * ============================================================================
 */

import * as React from 'react'
import { FilePicker, ToolDialog } from '../pdf-client'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { DialogFooter } from '@/components/ui/dialog'
import { Loader2, Download, FileCode, AlertTriangle, CheckCircle2, Eye } from 'lucide-react'
import { toast } from 'sonner'
import { saveAs } from 'file-saver'
import type { PdfTool } from '../pdf-tools'

function humanSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

const SAMPLE_HTML = `<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: Georgia, serif; color: #222; line-height: 1.6; }
  h1 { color: #b45309; border-bottom: 2px solid #b45309; padding-bottom: 8px; }
  h2 { color: #92400e; margin-top: 24px; }
  .meta { color: #6b7280; font-size: 13px; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { border: 1px solid #d1d5db; padding: 8px 12px; text-align: left; }
  th { background: #fef3c7; }
  @page { margin: 15mm; }
</style>
</head>
<body>
  <h1>Sample Document</h1>
  <div class="meta">Generated by PDF Forge HTML→PDF</div>

  <h2>Introduction</h2>
  <p>This is a demonstration of genuine browser-rendered PDF generation.
  The text is selectable, fonts are real, and print CSS is respected.</p>

  <h2>Feature Table</h2>
  <table>
    <tr><th>Feature</th><th>Supported</th></tr>
    <tr><td>Print CSS</td><td>Yes</td></tr>
    <tr><td>Vector text</td><td>Yes</td></tr>
    <tr><td>A4 / Letter</td><td>Yes</td></tr>
    <tr><td>Page breaks</td><td>Yes</td></tr>
  </table>
</body>
</html>`

export function HtmlToPdfTool({ tool, isBn, open, onOpenChange }: {
  tool: PdfTool
  isBn: boolean
  open: boolean
  onOpenChange: (v: boolean) => void
}) {
  const [files, setFiles] = React.useState<File[]>([])
  const [html, setHtml] = React.useState<string>(SAMPLE_HTML)
  const [pageSize, setPageSize] = React.useState<'A4' | 'Letter' | 'Legal'>('A4')
  const [orientation, setOrientation] = React.useState<'portrait' | 'landscape'>('portrait')
  const [printBackground, setPrintBackground] = React.useState(true)
  const [scale, setScale] = React.useState(1)
  const [marginTop, setMarginTop] = React.useState('0.4in')
  const [marginBottom, setMarginBottom] = React.useState('0.4in')
  const [displayHeaderFooter, setDisplayHeaderFooter] = React.useState(false)
  const [pageRanges, setPageRanges] = React.useState('')
  const [busy, setBusy] = React.useState(false)
  const [progress, setProgress] = React.useState(0)
  const [result, setResult] = React.useState<{ size: number } | null>(null)

  const bn = (s: string | number) =>
    isBn ? String(s).replace(/[0-9]/g, (d) => '০১২৩৪৫৬৭৮৯'[Number(d)]) : String(s)

  const onFileChange = async (newFiles: File[]) => {
    setFiles(newFiles)
    if (newFiles.length > 0) {
      const text = await newFiles[0].text()
      setHtml(text)
    }
  }

  const generate = async () => {
    if (!html.trim()) {
      toast.error(isBn ? 'HTML কনটেন্ট দিন।' : 'Enter HTML content.')
      return
    }
    if (html.length > 2 * 1024 * 1024) {
      toast.error(isBn ? 'HTML 2MB সীমা ছাড়িয়েছে।' : 'HTML exceeds 2MB limit.')
      return
    }
    setBusy(true)
    setProgress(20)
    try {
      setProgress(40)
      const response = await fetch('/api/html-to-pdf', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          html,
          pageSize,
          orientation,
          printBackground,
          scale,
          margin: { top: marginTop, bottom: marginBottom, left: '0.4in', right: '0.4in' },
          displayHeaderFooter,
          pageRanges: pageRanges || undefined,
        }),
      })
      setProgress(70)
      if (!response.ok) {
        const err = await response.json().catch(() => ({ error: 'Generation failed' }))
        throw new Error(err.error || 'Generation failed')
      }
      const blob = await response.blob()
      setProgress(90)
      saveAs(blob, 'html-to-pdf.pdf')
      setProgress(100)
      setResult({ size: blob.size })
      toast.success(
        isBn
          ? `পিডিএফ তৈরি হয়েছে (${humanSize(blob.size)})`
          : `PDF generated (${humanSize(blob.size)})`
      )
    } catch (err) {
      console.error('[HTML→PDF]', err)
      toast.error(err instanceof Error ? err.message : 'Generation failed.')
    } finally {
      setBusy(false)
      setProgress(0)
    }
  }

  return (
    <ToolDialog tool={tool} isBn={isBn} open={open} onOpenChange={onOpenChange}>
      <div className="space-y-4">
        <div className="space-y-2">
          <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
            {isBn ? 'HTML ফাইল (ঐচ্ছিক)' : 'HTML File (optional)'}
          </Label>
          <FilePicker isBn={isBn} files={files} onFiles={onFileChange} accept=".html,.htm" />
          <p className="text-xs text-muted-foreground">
            {isBn ? 'অথবা নিচে সরাসরি HTML লিখুন।' : 'Or paste/type HTML directly below.'}
          </p>
        </div>

        <div className="space-y-2">
          <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
            {isBn ? 'HTML কনটেন্ট' : 'HTML Content'}
          </Label>
          <Textarea
            value={html}
            onChange={(e) => { setHtml(e.target.value); setResult(null) }}
            className="min-h-[200px] font-mono text-xs"
            placeholder="<!DOCTYPE html>..."
            disabled={busy}
          />
          <p className="text-xs text-muted-foreground">
            {bn(html.length)} / 2,097,152 {isBn ? 'বাইট' : 'bytes'}
          </p>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-2">
            <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              {isBn ? 'পেজ সাইজ' : 'Page Size'}
            </Label>
            <Select value={pageSize} onValueChange={(v: any) => setPageSize(v)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="A4">A4</SelectItem>
                <SelectItem value="Letter">Letter</SelectItem>
                <SelectItem value="Legal">Legal</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              {isBn ? 'অরিয়েন্টেশন' : 'Orientation'}
            </Label>
            <Select value={orientation} onValueChange={(v: any) => setOrientation(v)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="portrait">{isBn ? 'পোর্ট্রেট' : 'Portrait'}</SelectItem>
                <SelectItem value="landscape">{isBn ? 'ল্যান্ডস্কেপ' : 'Landscape'}</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-2">
            <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              {isBn ? 'স্কেল' : 'Scale'}
            </Label>
            <Input
              type="number"
              min={0.1}
              max={2}
              step={0.1}
              value={scale}
              onChange={(e) => setScale(parseFloat(e.target.value) || 1)}
              disabled={busy}
            />
          </div>
          <div className="space-y-2">
            <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              {isBn ? 'পেজ রেঞ্জ (ঐচ্ছিক)' : 'Page Ranges (opt)'}
            </Label>
            <Input
              value={pageRanges}
              onChange={(e) => setPageRanges(e.target.value)}
              placeholder="1-5"
              disabled={busy}
            />
          </div>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-2">
            <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              {isBn ? 'উপরের মার্জিন' : 'Top Margin'}
            </Label>
            <Input value={marginTop} onChange={(e) => setMarginTop(e.target.value)} disabled={busy} />
          </div>
          <div className="space-y-2">
            <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              {isBn ? 'নিচের মার্জিন' : 'Bottom Margin'}
            </Label>
            <Input value={marginBottom} onChange={(e) => setMarginBottom(e.target.value)} disabled={busy} />
          </div>
        </div>

        <div className="flex items-center gap-4">
          <label className="flex items-center gap-2 text-xs cursor-pointer">
            <input
              type="checkbox"
              checked={printBackground}
              onChange={(e) => setPrintBackground(e.target.checked)}
              className="rounded"
            />
            <span>{isBn ? 'ব্যাকগ্রাউন্ড প্রিন্ট করুন' : 'Print backgrounds'}</span>
          </label>
          <label className="flex items-center gap-2 text-xs cursor-pointer">
            <input
              type="checkbox"
              checked={displayHeaderFooter}
              onChange={(e) => setDisplayHeaderFooter(e.target.checked)}
              className="rounded"
            />
            <span>{isBn ? 'হেডার/ফুটার (পেজ নম্বর)' : 'Header/Footer (page numbers)'}</span>
          </label>
        </div>

        <div className="rounded-lg border border-blue-500/30 bg-blue-500/5 p-3">
          <div className="flex gap-2">
            <FileCode className="h-4 w-4 shrink-0 text-blue-600 mt-0.5" />
            <p className="text-xs text-muted-foreground">
              {isBn
                ? 'আসল ব্রাউজার রেন্ডারিং (Chromium)। প্রিন্ট CSS, ভেক্টর টেক্সট, ওয়েব ফন্ট সাপোর্টেড। HTML সার্ভারে প্রসেস হয়, সংরক্ষণ করা হয় না।'
                : 'Genuine browser rendering (Chromium). Print CSS, vector text, web fonts supported. HTML is processed server-side, not stored.'}
            </p>
          </div>
        </div>

        <Button onClick={generate} disabled={!html.trim() || busy} className="w-full" variant="secondary">
          {busy ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />{isBn ? 'পিডিএফ তৈরি হচ্ছে…' : 'Generating PDF…'}</> : <><Download className="mr-2 h-4 w-4" />{isBn ? 'পিডিএফ তৈরি করুন' : 'Generate PDF'}</>}
        </Button>

        {busy && progress > 0 && (
          <div className="space-y-2">
            <div className="h-2 overflow-hidden rounded-full bg-muted">
              <div className="h-full bg-gradient-to-r from-blue-500 to-cyan-500 transition-all" style={{ width: `${progress}%` }} />
            </div>
            <p className="text-center text-xs text-muted-foreground">{bn(progress)}%</p>
          </div>
        )}

        {result && !busy && (
          <div className="rounded-lg border border-green-500/30 bg-green-500/5 p-3 space-y-1">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-600" />
              <span className="text-xs font-medium">{isBn ? 'পিডিএফ প্রস্তুত' : 'PDF Ready'}</span>
            </div>
            <p className="text-xs text-muted-foreground">{isBn ? `সাইজ: ${humanSize(result.size)}` : `Size: ${humanSize(result.size)}`}</p>
            <div className="flex items-start gap-2 text-xs text-muted-foreground">
              <Eye className="h-3.5 w-3.5 shrink-0 mt-0.5" />
              <span>{isBn ? 'ডাউনলোড করে যাচাই করুন — টেক্সট সিলেক্টেবল হবে।' : 'Open the download to verify — text should be selectable.'}</span>
            </div>
          </div>
        )}

        <DialogFooter>
          <Button variant="outline" onClick={() => { setResult(null); onOpenChange(false) }}>{isBn ? 'বন্ধ করুন' : 'Close'}</Button>
        </DialogFooter>
      </div>
    </ToolDialog>
  )
}
