'use client'

import * as React from "react"

export type Lang = 'en' | 'bn'

type Ctx = {
  lang: Lang
  setLang: (l: Lang) => void
  toggle: () => void
  t: (key: string) => string
  tr: (en: string) => string
}

const LanguageContext = React.createContext<Ctx | null>(null)

const STORAGE_KEY = 'nextgen-lang'

const translations: Record<Lang, Record<string, string>> = {
  en: {
    'nav.about': 'About', 'nav.services': 'Services', 'nav.industries': 'Industries',
    'nav.caseStudies': 'Case Studies', 'nav.pricing': 'Pricing', 'nav.whyUs': 'Why Us',
    'nav.blog': 'Blog', 'nav.contact': 'Contact',
    'cta.bookCall': 'Book Strategy Call', 'cta.bookFreeCall': 'Book a Free Strategy Call',
    'cta.exploreServices': 'Explore Services', 'cta.startFreeAudit': 'Start free audit',
    'cta.getThisStack': 'Get this stack', 'cta.subscribe': 'Subscribe', 'cta.sendMessage': 'Send Message',
    'hero.badge': 'AI Sales Automation Agency · Bangladesh',
    'hero.title1': 'Turn Your Business into an', 'hero.title2': 'AI-Powered Sales Machine',
    'hero.subtitle': 'We help businesses in Bangladesh automate marketing, sales, customer communication and operations with Artificial Intelligence — so you generate qualified leads and book calls 24/7, on autopilot.',
    'hero.trustedBy': 'Trusted by 120+ leading businesses across Bangladesh',
    'hero.freeCall': '30-min free call', 'hero.noCommitment': 'No commitment', 'hero.bilingual': 'Bangla & English',
    'problem.eyebrow': 'The Problem', 'problem.title1': 'Running a business the old way is',
    'problem.title2': 'expensive', 'problem.title3': '& slow',
    'problem.subtitle': "While you're stuck doing manual work, your competitors are using AI to respond instantly, automate everything and win your customers.",
    'problem.warning': "Every day you wait, you're losing qualified leads and revenue to competitors who already automated.",
    'solution.eyebrow': 'Our Solution', 'solution.title1': 'One AI-powered system that',
    'solution.title2': 'runs your growth', 'solution.title3': 'on autopilot',
    'solution.subtitle': "We design, build and manage your entire AI + automation stack — from first click to closed deal — so you can scale without scaling headcount.",
    'services.eyebrow': 'What We Do', 'services.title1': 'AI & automation services that', 'services.title2': 'drive revenue',
    'services.subtitle': 'Twelve specialised services covering the entire customer journey — from generating leads to closing deals and automating operations.',
    'industries.eyebrow': 'Industries We Serve', 'industries.title1': 'Built for the businesses that', 'industries.title2': 'power Bangladesh',
    'industries.subtitle': "From small businesses to corporates, we tailor AI + automation to your industry's exact workflows and customer expectations.",
    'howItWorks.eyebrow': 'How It Works', 'howItWorks.title1': 'From first call to', 'howItWorks.title2': 'automated growth', 'howItWorks.title3': 'in 4 steps',
    'howItWorks.subtitle': 'A proven, transparent process that gets your AI systems live in weeks — not months.',
    'byNumbers.eyebrow': 'By the Numbers', 'byNumbers.title1': 'Results that speak', 'byNumbers.title2': 'louder than promises',
    'byNumbers.subtitle': 'Real outcomes from real Bangladeshi businesses we\'ve automated with AI over the past two years.',
    'roi.eyebrow': 'ROI Calculator', 'roi.title1': 'See your potential', 'roi.title2': 'ROI in 10 seconds',
    'roi.subtitle': 'Adjust the sliders to estimate how much extra revenue and time AI automation could generate for your business.',
    'testimonials.eyebrow': 'Testimonials', 'testimonials.title1': 'Loved by businesses', 'testimonials.title2': 'across Bangladesh',
    'testimonials.subtitle': "Don't take our word for it — hear what our clients say about working with NextGen Digital Studio.",
    'pricing.eyebrow': 'Pricing', 'pricing.title1': 'Simple, transparent', 'pricing.title2': 'monthly plans',
    'pricing.subtitle': "No hidden fees, no long lock-ins. Pick a plan, we build your system, and you only pay while it's generating ROI.",
    'pricing.mostPopular': 'Most Popular', 'pricing.needCustom': 'Need something custom?',
    'comparison.eyebrow': 'Why We\'re Different', 'comparison.title1': 'NextGen vs.', 'comparison.title2': 'the rest',
    'comparison.subtitle': 'Most agencies sell hours. We sell automated outcomes. Here\'s exactly how working with us compares to the alternatives.',
    'caseStudies.eyebrow': 'Case Studies', 'caseStudies.title1': 'Real businesses.', 'caseStudies.title2': 'Real results.',
    'caseStudies.subtitle': 'See how Bangladeshi companies are generating more leads, cutting costs and scaling with our AI + automation systems.',
    'team.eyebrow': 'Our Story', 'team.title1': 'The team building', 'team.title2': "Bangladesh's AI future",
    'team.subtitle': "We're a Jessore-based squad of AI engineers, growth specialists and automation architects obsessed with one thing: your revenue.",
    'faq.eyebrow': 'FAQ', 'faq.title1': 'Questions?', 'faq.title2': "We've got answers.",
    'faq.subtitle': 'Everything you need to know about working with NextGen Digital Studio.',
    'ctaBand.title': 'Ready to automate your growth?',
    'ctaBand.subtitle': 'Book a free 30-minute strategy call. We\'ll audit your business and design a custom AI + automation roadmap — no obligation.',
    'ctaBand.freeCall': '30-min free call', 'ctaBand.noCommitment': 'No commitment',
    'ctaBand.repliesWithin': 'Replies within 2 hours · Jessore, Bangladesh',
    'contact.eyebrow': 'Contact', 'contact.title1': "Let's build your", 'contact.title2': 'AI growth engine',
    'contact.subtitle': 'Send us a message or book a call. We typically reply within 2 hours during business hours.',
    'blog.eyebrow': 'Insights', 'blog.title1': 'From the', 'blog.title2': 'NextGen blog',
    'blog.subtitle': 'Practical guides on AI, automation and growth for Bangladeshi businesses.',
    'footer.newsletterTitle': 'Get AI growth insights every week',
    'footer.newsletterDesc': 'Join 3,000+ Bangladeshi founders getting practical automation & AI tips. No spam, unsubscribe anytime.',
    'footer.emailPlaceholder': 'Enter your email', 'footer.subscribed': 'You\'re subscribed! Check your inbox to confirm.',
    'footer.aboutDesc': "Bangladesh's premier AI Sales Automation Agency. We help businesses automate marketing, sales and operations with Artificial Intelligence.",
    'footer.privacyPolicy': 'Privacy Policy', 'footer.termsOfService': 'Terms of Service', 'footer.careers': 'Careers',
    'footer.apiDocs': 'API Docs', 'footer.staff': 'Staff', 'footer.allRights': 'All rights reserved.',
    'footer.madeIn': 'Made in', 'footer.bangladesh': 'Bangladesh',
    'urgency.onlyX': 'Only 5 free strategy calls available this week',
    'lang.toggle': 'বাংলা',
    'cta.viewAllServices': 'View all',
    'footer.services': 'Services', 'footer.company': 'Company', 'footer.industries': 'Industries',
    'aiDemo.eyebrow': 'See It In Action', 'aiDemo.title1': 'Experience our AI', 'aiDemo.title2': 'before you book',
    'aiDemo.subtitle': "Don't just take our word for it. Watch how our AI agents handle real customer conversations — in Bangla and English, 24/7.",
    'aiDemo.tryOnBusiness': 'Try it on my business',
    'why.eyebrow': 'Why Choose Us',
    'why.title1': "Bangladesh's most results-obsessed", 'why.title2': 'AI automation agency',
    'why.subtitle': "We're not just developers — we're growth partners. Every system we build is engineered around one goal: more qualified leads, more booked calls, more revenue.",
    'why.workWithUs': 'Work with our team',
    'roi.businessSize': '1. What best describes your business?',
    'roi.leadResponse': 'Lead response Improvement',
    'roi.leadResponseHint': 'Faster AI response typically converts 20–200% more leads',
    'roi.hoursSaved': 'Hours Saved Per Week',
    'roi.hoursSavedHint': 'Time freed from manual follow-ups, data entry & support',
    'roi.disclaimer': 'Estimates based on industry benchmarks from our 120+ client deployments across Bangladesh. Actual results vary.',
    'roi.yourProjected': 'YOUR PROJECTED YEARLY IMPACT',
    'roi.totalValue': 'Total value created per year',
    'roi.extraLeads': 'Extra qualified leads / mo',
    'roi.revenueUplift': 'Revenue uplift / year',
    'roi.hoursSavedYear': 'Hours saved / year',
    'roi.labourSaved': 'Labour cost saved',
    'roi.roiMultiple': 'Estimated ROI multiple',
    'roi.getDetailedROI': 'Get my detailed ROI breakdown',
    'audit.eyebrow': 'Free AI Audit Tool',
    'audit.title1': 'How much revenue is', 'audit.title2': 'slipping through the cracks?',
    'audit.subtitle': "Answer 4 quick questions and get an instant AI-readiness score plus a personalised report on where you're losing leads.",
    'audit.getScore': 'Get your free AI-readiness score',
    'audit.takesSeconds': 'Takes 60 seconds. No signup required to see your score. Get a personalised report on where AI can grow your revenue.',
    'audit.4questions': '4 questions', 'audit.instantScore': 'Instant score', 'audit.freeReport': 'Free report',
    'audit.startFreeAudit': 'Start free audit',
    'audit.yourScore': 'YOUR AI-READINESS SCORE',
    'audit.opportunities': 'BIGGEST OPPORTUNITIES FOR YOU',
    'audit.getFullReport': 'Get my full report',
    'audit.bookCallInstead': 'Book a strategy call instead',
    'audit.reportOnItsWay': 'Your report is on its way!',
    'audit.checkInbox': 'Check your inbox in the next few minutes.',
    'audit.fastTrack': 'Want to fast-track your results?',
    'audit.bookStrategyCall': 'Book my strategy call',
    'audit.getReport': 'Get your full audit report',
    'audit.emailReport': "We'll email you a detailed breakdown of your score plus 3 personalised AI automation recommendations.",
    'audit.fullName': 'Full name', 'audit.phone': 'Phone / WhatsApp', 'audit.email': 'Email',
    'audit.company': 'Company', 'audit.yourIndustry': 'Your industry',
    'audit.emailMeReport': 'Email me my report',
    'audit.noSpam': 'By booking, you agree to be contacted by NextGen Digital Studio.',
    'configurator.eyebrow': 'Build Your Stack',
    'configurator.title1': 'Design your custom', 'configurator.title2': 'AI automation stack',
    'configurator.subtitle': 'Pick the services you need and see your monthly price update live. Bundle 2+ services for automatic discounts — no hidden fees.',
    'configurator.yourStack': 'Your Stack', 'configurator.reset': 'Reset',
    'configurator.monthlyTotal': 'Monthly total', 'configurator.subtotal': 'Subtotal',
    'configurator.youSave': 'You save', 'configurator.getThisStack': 'Get this stack',
    'configurator.bundleDiscount': 'bundle discount unlocked!',
    'configurator.freeCall': 'Free strategy call · No commitment · Cancel anytime',
    'configurator.selectServices': 'Select services to build your custom stack →',
    'workflow.eyebrow': 'Workflow Builder',
    'workflow.title1': 'Visualize your', 'workflow.title2': 'AI sales funnel',
    'workflow.subtitle': 'Drag to reorder steps, add new ones, and run the flow to see how an AI-powered funnel turns visitors into booked calls — automatically.',
    'workflow.yourFunnel': 'Your Funnel', 'workflow.steps': 'steps', 'workflow.reset': 'Reset',
    'workflow.runFlow': 'Run Flow', 'workflow.running': 'Running...',
    'workflow.addStep': 'Add a step', 'workflow.available': 'available',
    'workflow.emptyFunnel': 'Your funnel is empty. Add steps from the library →',
    'workflow.addSteps': 'Add steps',
    'workflow.funnelProjection': 'FUNNEL PROJECTION',
    'workflow.automationSteps': 'Automation steps', 'workflow.alwaysRunning': 'Always running',
    'workflow.leadResponse': 'Lead response', 'workflow.estConversion': 'Est. conversion lift',
    'workflow.howThisWorks': 'How this funnel works',
    'workflow.buildForMe': 'Build this for me',
    'workflow.step1': 'A visitor lands on your site',
    'workflow.step2': 'AI engages them instantly in Bangla/English',
    'workflow.step3': 'Lead is qualified & tagged automatically',
    'workflow.step4': 'Follow-ups run until a call is booked',
    'videoTest.eyebrow': 'Video Stories', 'videoTest.title1': 'Hear it straight from',
    'videoTest.title2': 'our clients',
    'videoTest.subtitle': 'Real Bangladeshi business owners share how NextGen Digital Studio transformed their growth with AI automation.',
    'videoTest.becomeNext': 'Become our next success story',
    'guarantees.eyebrow': 'Our Promises to You',
    'pricingFaq.eyebrow': 'Pricing Questions',
    'pricingFaq.title1': 'Everything you need to know about', 'pricingFaq.title2': 'pricing',
    'pricingFaq.subtitle': 'Still have questions? Book a free strategy call and we\'ll answer everything.',
    'pricingFaq.stillHaveQuestions': 'Still have questions? Talk to us',
    'awards.eyebrow': 'Awards & Recognition',
    'awards.title1': 'Recognised for', 'awards.title2': 'delivering results',
    'awards.subtitle': "We're proud to be recognised by Bangladesh's tech and business community — and certified by the platforms we build on.",
    'awards.certifiedPartners': 'Certified & Authorized Partners',
    'team.meetPeople': 'Meet the people behind the AI',
    'team.teamDesc': 'A focused team — no bloat, no handoffs, just specialists who ship.',
    'team.workWithUs': 'Work with our team',
    'partner.eyebrow': 'Partner Program', 'partner.title1': 'Earn while you', 'partner.title2': 'refer',
    'partner.subtitle': 'Join 40+ agencies and consultants earning recurring commission by referring Bangladeshi businesses to NextGen Digital Studio.',
    'partner.commission': 'commission', 'partner.getDashboard': 'Get your dashboard',
    'techStack.eyebrow': 'Our Tech Stack',
    'techStack.title1': 'Powered by the world\'s best',
    'techStack.title2': 'AI & automation tools',
    'techStack.subtitle': 'We integrate enterprise-grade platforms to build systems that are reliable, scalable and future-proof.',
    'kb.eyebrow': 'Knowledge Base', 'kb.title1': 'Learn how to', 'kb.title2': 'automate your business',
    'kb.subtitle': 'Practical guides, tutorials and playbooks on AI, automation and growth — written for Bangladeshi businesses.',
    'kb.searchPlaceholder': 'Search articles... (e.g. WhatsApp, CRM, leads)',
    'kb.bookCall': 'Want a personalised automation plan?',
    'kb.bookCallLink': 'Book a free strategy call',
    'freeTools.eyebrow': 'Free Tools & Resources',
    'freeTools.title1': 'Download free tools to', 'freeTools.title2': 'automate smarter',
    'freeTools.subtitle': 'Templates, checklists, ebooks and calculators — battle-tested with 120+ Bangladeshi businesses. Free to download.',
    'integrations.eyebrow': 'Integrations Directory',
    'integrations.title1': 'We connect with', 'integrations.title2': '27+ tools',
    'integrations.title3': 'you already use',
    'integrations.subtitle': 'Your AI automation stack is only as good as its integrations. We plug into the platforms your business runs on — seamlessly.',
    'integrations.searchPlaceholder': 'Search 27+ integrations...',
    'integrations.dontSeeTool': "Don't see your tool?",
    'integrations.dontSeeDesc': 'We build custom integrations for any platform with an API.',
    'integrations.requestIntegration': 'Request integration',
    'careers.eyebrow': 'Careers', 'careers.title1': 'Build the future of',
    'careers.title2': 'AI in Bangladesh',
    'careers.subtitle': 'We are looking for sharp, passionate people who want to ship real AI products that grow Bangladeshi businesses. Join us.',
    'careers.openPositions': 'Open positions',
    'careers.dontSeeRole': 'Do not see your role?',
    'careers.sendGeneral': 'Send a general application',
    'status.eyebrow': 'System Status', 'status.title1': 'All systems', 'status.title2': 'operational',
    'status.subtitle': 'We monitor our platform 24/7. Here\'s the real-time status of every service we run for our clients.',
    'status.allOperational': 'All Systems Operational',
    'status.updatedJustNow': 'Updated just now · 99.96% uptime over the last 30 days',
    'status.uptime30day': '30-day uptime', 'status.operational': 'Operational',
    'status.recentIncidents': 'Recent Incidents', 'status.haveIssue': 'Have an issue?',
    'contact.fullName': 'Full name', 'contact.phone': 'Phone', 'contact.email': 'Email',
    'contact.company': 'Company', 'contact.serviceInterested': 'Service interested in',
    'contact.selectService': 'Select a service', 'contact.message': 'Message',
    'contact.tellAboutProject': 'Tell us about your project and goals...',
    'contact.sendMessage': 'Send Message', 'contact.sending': 'Sending...',
    'contact.messageSent': 'Message sent!',
    'contact.sentDesc': 'Thank you for reaching out. Our team will respond within 24 hours.',
    'contact.sendAnother': 'Send another message',
    'contact.followWork': 'Follow our work',
    // Chat widget UI
    'chat.title': 'NextGen AI Assistant',
    'chat.online': '● Online · replies instantly',
    'chat.clearChat': 'Clear chat',
    'chat.bookCall': 'Book a free strategy call',
    'chat.placeholder': 'Type your message...',
    'chat.poweredBy': 'Powered by NextGen AI',
    'chat.callUs': 'Call us',
    'chat.urgentEnquiry': 'for urgent enquiries',
    'chat.suggestion1': 'What services do you offer?',
    'chat.suggestion2': 'How much does it cost?',
    'chat.suggestion3': 'Can you automate WhatsApp?',
    'chat.suggestion4': 'I run a real estate business',
    'chat.ariaOpen': 'Open AI assistant chat',
    'chat.ariaClear': 'Clear chat history',
    'chat.ariaClose': 'Close chat',
    'chat.ariaSend': 'Send message',
    // Hero chat demo + floating stats
    'hero.aiAgent': 'AI Sales Agent',
    'hero.onlineBilingual': '● Online · Bangla & English',
    'hero.chatUser1': "Hi, I'm interested in your apartment in Gulshan. Is it available?",
    'hero.chatUser2': 'Yes please, Saturday 11am works.',
    'hero.chatSuccess': 'Site visit booked · Lead qualified · CRM updated',
    'hero.qualifiedLeads': 'Qualified leads',
    'hero.responseTime': 'Response time',
    'hero.trustedPrefix': 'Trusted by',
    'hero.businessesCount': '120+ businesses',
  },
  bn: {
    'nav.about': 'আমাদের সম্পর্কে', 'nav.services': 'সেবাসমূহ', 'nav.industries': 'শিল্পখাত',
    'nav.caseStudies': 'কেস স্টাডি', 'nav.pricing': 'প্রাইসিং', 'nav.whyUs': 'কেন আমরা',
    'nav.blog': 'ব্লগ', 'nav.contact': 'যোগাযোগ',
    'cta.bookCall': 'স্ট্র্যাটেজি কল বুক করুন', 'cta.bookFreeCall': 'ফ্রি স্ট্র্যাটেজি কল বুক করুন',
    'cta.exploreServices': 'সেবাসমূহ দেখুন', 'cta.startFreeAudit': 'ফ্রি অডিট শুরু করুন',
    'cta.getThisStack': 'এই স্ট্যাক নিন', 'cta.subscribe': 'সাবস্ক্রাইব', 'cta.sendMessage': 'বার্তা পাঠান',
    'hero.badge': 'এআই সেলস অটোমেশন এজেন্সি · বাংলাদেশ',
    'hero.title1': 'আপনার ব্যবসাকে করুন', 'hero.title2': 'এআই-চালিত সেলস মেশিন',
    'hero.subtitle': 'আমরা বাংলাদেশের ব্যবসাকে মার্কেটিং, সেলস, কাস্টমার কমিউনিকেশন ও অপারেশনস অটোমেট করতে সাহায্য করি কৃত্রিম বুদ্ধিমত্তা দিয়ে — যাতে আপনি যোগ্য লিড পান এবং ২৪/৭ কল বুক করতে পারেন, স্বয়ংক্রিয়ভাবে।',
    'hero.trustedBy': 'বাংলাদেশের ১২০+ শীর্ষ ব্যবসা আমাদের উপর আস্থা রাখে',
    'hero.freeCall': '৩০ মিনিট ফ্রি কল', 'hero.noCommitment': 'কোনো বাধ্যবাধকতা নেই', 'hero.bilingual': 'বাংলা ও ইংরেজি',
    'problem.eyebrow': 'সমস্যা', 'problem.title1': 'পুরনো পদ্ধতিতে ব্যবসা চালানো',
    'problem.title2': 'ব্যয়বহুল', 'problem.title3': 'ও ধীর',
    'problem.subtitle': 'আপনি ম্যানুয়াল কাজে ব্যস্ত থাকার সময় আপনার প্রতিযোগীরা এআই ব্যবহার করে তাৎক্ষণিক সাড়া দিচ্ছে, সবকিছু অটোমেট করছে এবং আপনার কাস্টমারদের জয় করছে।',
    'problem.warning': 'প্রতিদিন আপনি অপেক্ষা করছেন, প্রতিদিন আপনি যোগ্য লিড ও রাজস্ব হারাচ্ছেন এমন প্রতিযোগীদের কাছে যারা ইতিমধ্যে অটোমেট করেছে।',
    'solution.eyebrow': 'আমাদের সমাধান', 'solution.title1': 'একটি এআই-চালিত সিস্টেম যা',
    'solution.title2': 'আপনার বৃদ্ধি চালায়', 'solution.title3': 'অটোপাইলটে',
    'solution.subtitle': 'আমরা আপনার সম্পূর্ণ এআই + অটোমেশন স্ট্যাক ডিজাইন, বিল্ড ও ম্যানেজ করি — প্রথম ক্লিক থেকে ক্লোজড ডিল পর্যন্ত — যাতে আপনি হেডকাউন্ট বাড়ানো ছাড়াই স্কেল করতে পারেন।',
    'services.eyebrow': 'আমরা যা করি', 'services.title1': 'এআই ও অটোমেশন সেবা যা', 'services.title2': 'রাজস্ব বাড়ায়',
    'services.subtitle': 'বারোটি বিশেষায়িত সেবা — লিড জেনারেশন থেকে ডিল ক্লোজ এবং অপারেশনস অটোমেশন পর্যন্ত সম্পূর্ণ কাস্টমার জার্নি কভার করে।',
    'industries.eyebrow': 'যেসব শিল্পখাতে আমরা কাজ করি', 'industries.title1': 'বাংলাদেশের যেসব ব্যবসার জন্য', 'industries.title2': 'আমরা তৈরি',
    'industries.subtitle': 'ছোট ব্যবসা থেকে কর্পোরেট — আমরা আপনার ইন্ডাস্ট্রির সঠিক ওয়ার্কফ্লো ও কাস্টমার প্রত্যাশা অনুযায়ী এআই + অটোমেশন তৈরি করি।',
    'howItWorks.eyebrow': 'কিভাবে কাজ করে', 'howItWorks.title1': 'প্রথম কল থেকে', 'howItWorks.title2': 'অটোমেটেড গ্রোথ', 'howItWorks.title3': '৪টি ধাপে',
    'howItWorks.subtitle': 'একটি প্রমাণিত, স্বচ্ছ প্রক্রিয়া যা আপনার এআই সিস্টেম সপ্তাহের মধ্যে লাইভ করে — মাস নয়।',
    'byNumbers.eyebrow': 'সংখ্যায়', 'byNumbers.title1': 'ফলাফল যা প্রতিশ্রুতির চেয়ে', 'byNumbers.title2': 'বেশি কথা বলে',
    'byNumbers.subtitle': 'বাংলাদেশের বাস্তব ব্যবসার বাস্তব ফলাফল — গত দুই বছরে এআই দিয়ে অটোমেট করা।',
    'roi.eyebrow': 'ROI ক্যালকুলেটর', 'roi.title1': 'আপনার সম্ভাব্য', 'roi.title2': 'ROI ১০ সেকেন্ডে দেখুন',
    'roi.subtitle': 'স্লাইডার সমন্বয় করে অনুমান করুন এআই অটোমেশন আপনার ব্যবসার জন্য কতটা অতিরিক্ত রাজস্ব ও সময় তৈরি করতে পারে।',
    'testimonials.eyebrow': 'টেস্টিমোনিয়াল', 'testimonials.title1': 'বাংলাদেশের', 'testimonials.title2': 'ব্যবসাগুলোর ভালোবাসা পেয়েছি',
    'testimonials.subtitle': 'আমাদের কথা নয় — শুনুন আমাদের ক্লায়েন্টরা কী বলছেন NextGen Digital Studio এর সাথে কাজ করার অভিজ্ঞতা নিয়ে।',
    'pricing.eyebrow': 'প্রাইসিং', 'pricing.title1': 'সহজ, স্বচ্ছ', 'pricing.title2': 'মাসিক প্ল্যান',
    'pricing.subtitle': 'কোনো লুকানো ফি নেই, কোনো দীর্ঘ চুক্তি নেই। প্ল্যান বাছুন, আমরা সিস্টেম তৈরি করি, এবং আপনি শুধু ততক্ষণ পর্যন্ত পরিশোধ করেন যতক্ষণ এটি ROI তৈরি করে।',
    'pricing.mostPopular': 'সবচেয়ে জনপ্রিয়', 'pricing.needCustom': 'কাস্টম কিছু দরকার?',
    'comparison.eyebrow': 'কেন আমরা আলাদা', 'comparison.title1': 'NextGen বনাম', 'comparison.title2': 'অন্যরা',
    'comparison.subtitle': 'বেশিরভাগ এজেন্সি ঘণ্টা বিক্রি করে। আমরা অটোমেটেড ফলাফল বিক্রি করি। আমাদের সাথে কাজ করা কিভাবে অন্যদের তুলনায় আলাদা, তা এখানে।',
    'caseStudies.eyebrow': 'কেস স্টাডি', 'caseStudies.title1': 'বাস্তব ব্যবসা।', 'caseStudies.title2': 'বাস্তব ফলাফল।',
    'caseStudies.subtitle': 'দেখুন বাংলাদেশের কোম্পানিগুলো কিভাবে আমাদের এআই + অটোমেশন সিস্টেম দিয়ে বেশি লিড তৈরি, খরচ কমায় এবং স্কেল করছে।',
    'team.eyebrow': 'আমাদের গল্প', 'team.title1': 'বাংলাদেশের এআই ভবিষ্যৎ', 'team.title2': 'তৈরি করছে যে টিম',
    'team.subtitle': 'আমরা যশোরভিত্তিক এআই ইঞ্জিনিয়ার, গ্রোথ স্পেশালিস্ট ও অটোমেশন আর্কিটেক্টের একটি টিম — একটি জিনিস নিয়ে আগ্রহী: আপনার রাজস্ব।',
    'faq.eyebrow': 'প্রশ্নোত্তর', 'faq.title1': 'প্রশ্ন আছে?', 'faq.title2': 'উত্তর আছে।',
    'faq.subtitle': 'NextGen Digital Studio এর সাথে কাজ করা সম্পর্কে যা যা জানতে হবে।',
    'ctaBand.title': 'আপনার গ্রোথ অটোমেট করতে প্রস্তুত?',
    'ctaBand.subtitle': 'ফ্রি ৩০-মিনিট স্ট্র্যাটেজি কল বুক করুন। আমরা আপনার ব্যবসা অডিট করে কাস্টম এআই + অটোমেশন রোডম্যাপ তৈরি করব — কোনো বাধ্যবাধকতা নেই।',
    'ctaBand.freeCall': '৩০ মিনিট ফ্রি কল', 'ctaBand.noCommitment': 'কোনো বাধ্যবাধকতা নেই',
    'ctaBand.repliesWithin': '২ ঘন্টার মধ্যে উত্তর · যশোর, বাংলাদেশ',
    'contact.eyebrow': 'যোগাযোগ', 'contact.title1': 'চলুন তৈরি করি আপনার', 'contact.title2': 'এআই গ্রোথ ইঞ্জিন',
    'contact.subtitle': 'বার্তা পাঠান বা কল বুক করুন। কর্মঘণ্টায় আমরা সাধারণত ২ ঘন্টার মধ্যে উত্তর দেই।',
    'blog.eyebrow': 'ইনসাইটস', 'blog.title1': 'NextGen', 'blog.title2': 'ব্লগ থেকে',
    'blog.subtitle': 'বাংলাদেশের ব্যবসার জন্য এআই, অটোমেশন ও গ্রোথের উপর বাস্তবমুখী গাইড।',
    'footer.newsletterTitle': 'প্রতি সপ্তাহে এআই গ্রোথ ইনসাইটস পান',
    'footer.newsletterDesc': '৩,০০০+ বাংলাদেশি প্রতিষ্ঠাতার সাথে যোগ দিন যারা বাস্তবমুখী অটোমেশন ও এআই টিপস পান। কোনো স্প্যাম নেই।',
    'footer.emailPlaceholder': 'ইমেইল লিখুন', 'footer.subscribed': 'সাবস্ক্রাইব হয়েছে! কনফার্মেশনের জন্য ইনবক্স চেক করুন।',
    'footer.aboutDesc': 'বাংলাদেশের প্রিমিয়াম এআই সেলস অটোমেশন এজেন্সি। আমরা ব্যবসাকে মার্কেটিং, সেলস ও অপারেশনস অটোমেট করতে সাহায্য করি কৃত্রিম বুদ্ধিমত্তা দিয়ে।',
    'footer.privacyPolicy': 'প্রাইভেসি পলিসি', 'footer.termsOfService': 'সেবার শর্তাবলী', 'footer.careers': 'ক্যারিয়ার',
    'footer.apiDocs': 'API ডকস', 'footer.staff': 'স্টাফ', 'footer.allRights': 'সর্বস্বত্ব সংরক্ষিত।',
    'footer.madeIn': 'তৈরি', 'footer.bangladesh': 'বাংলাদেশে',
    'urgency.onlyX': 'এই সপ্তাহে মাত্র ৫টি ফ্রি স্ট্র্যাটেজি কল উপলব্ধ',
    'lang.toggle': 'EN',
    'cta.viewAllServices': 'সব দেখুন',
    'footer.services': 'সেবাসমূহ', 'footer.company': 'কোম্পানি', 'footer.industries': 'শিল্পখাত',
    'aiDemo.eyebrow': 'নিজে দেখুন', 'aiDemo.title1': 'বুক করার আগে', 'aiDemo.title2': 'আমাদের এআই অনুভব করুন',
    'aiDemo.subtitle': 'শুধু আমাদের কথা বিশ্বাস করবেন না। দেখুন কিভাবে আমাদের এআই এজেন্ট বাস্তব কাস্টমার কথোপকথন পরিচালনা করে — বাংলা ও ইংরেজিতে, ২৪/৭।',
    'aiDemo.tryOnBusiness': 'আমার ব্যবসায় চেষ্টা করুন',
    'why.eyebrow': 'কেন আমরা', 'why.title1': 'বাংলাদেশের সবচেয়ে ফলাফল-আসক্ত', 'why.title2': 'এআই অটোমেশন এজেন্সি',
    'why.subtitle': 'আমরা শুধু ডেভেলপার নই — আমরা গ্রোথ পার্টনার। আমরা যে সিস্টেম তৈরি করি তার একটি লক্ষ্য: বেশি যোগ্য লিড, বেশি বুকড কল, বেশি রাজস্ব।',
    'why.workWithUs': 'আমাদের টিমের সাথে কাজ করুন',
    'roi.businessSize': '১. আপনার ব্যবসার ধরন কোনটি?',
    'roi.leadResponse': 'লিড রেসপন্স উন্নতি',
    'roi.leadResponseHint': 'দ্রুত এআই রেসপন্স সাধারণত ২০-২০০% বেশি লিড কনভার্ট করে',
    'roi.hoursSaved': 'সাপ্তাহিক সাশ্রয়িত সময়',
    'roi.hoursSavedHint': 'ম্যানুয়াল ফলো-আপ, ডেটা এন্ট্রি ও সাপোর্ট থেকে মুক্ত সময়',
    'roi.disclaimer': 'বাংলাদেশে আমাদের ১২০+ ক্লায়েন্ট ডিপ্লয়মেন্ট থেকে ইন্ডাস্ট্রি বেঞ্চমার্কের উপর ভিত্তি করে অনুমান। প্রকৃত ফলাফল ভিন্ন হতে পারে।',
    'roi.yourProjected': 'আপনার প্রজেক্টেড বার্ষিক প্রভাব',
    'roi.totalValue': 'বার্ষিক মোট মূল্য', 'roi.extraLeads': 'অতিরিক্ত যোগ্য লিড / মাস',
    'roi.revenueUplift': 'রাজস্ব বৃদ্ধি / বছর', 'roi.hoursSavedYear': 'সাশ্রয়িত সময় / বছর',
    'roi.labourSaved': 'শ্রম খরচ সাশ্রয়', 'roi.roiMultiple': 'আনুমানিক ROI মাল্টিপল',
    'roi.getDetailedROI': 'বিস্তারিত ROI ব্রেকডাউন পান',
    'audit.eyebrow': 'ফ্রি এআই অডিট টুল', 'audit.title1': 'কতটা রাজস্ব', 'audit.title2': 'ফসকে যাচ্ছে?',
    'audit.subtitle': '৪টি দ্রুত প্রশ্নের উত্তর দিন এবং তাৎক্ষণিক এআই-রেডিনেস স্কোর পান সাথে আপনি কোথায় লিড হারাচ্ছেন তার পার্সোনালাইজড রিপোর্ট।',
    'audit.getScore': 'ফ্রি এআই-রেডিনেস স্কোর পান',
    'audit.takesSeconds': '৬০ সেকেন্ড লাগে। স্কোর দেখতে সাইনআপ লাগে না। এআই কোথায় আপনার রাজস্ব বাড়াতে পারে তার পার্সোনালাইজড রিপোর্ট পান।',
    'audit.4questions': '৪টি প্রশ্ন', 'audit.instantScore': 'তাৎক্ষণিক স্কোর', 'audit.freeReport': 'ফ্রি রিপোর্ট',
    'audit.startFreeAudit': 'ফ্রি অডিট শুরু করুন', 'audit.yourScore': 'আপনার এআই-রেডিনেস স্কোর',
    'audit.opportunities': 'আপনার জন্য সবচেয়ে বড় সুযোগ', 'audit.getFullReport': 'সম্পূর্ণ রিপোর্ট পান',
    'audit.bookCallInstead': 'এর পরিবর্তে স্ট্র্যাটেজি কল বুক করুন', 'audit.reportOnItsWay': 'আপনার রিপোর্ট পাঠানো হচ্ছে!',
    'audit.checkInbox': 'পরবর্তী কয়েক মিনিটে আপনার ইনবক্স চেক করুন।', 'audit.fastTrack': 'ফলাফল দ্রুত পেতে চান?',
    'audit.bookStrategyCall': 'স্ট্র্যাটেজি কল বুক করুন', 'audit.getReport': 'সম্পূর্ণ অডিট রিপোর্ট পান',
    'audit.emailReport': 'আপনার ইমেইলে স্কোরের বিস্তারিত ব্রেকডাউন ও ৩টি পার্সোনালাইজড এআই অটোমেশন সুপারিশ পাঠাব।',
    'audit.fullName': 'পূর্ণ নাম', 'audit.phone': 'ফোন / হোয়াটসঅ্যাপ', 'audit.email': 'ইমেইল',
    'audit.company': 'কোম্পানি', 'audit.yourIndustry': 'আপনার ইন্ডাস্ট্রি',
    'audit.emailMeReport': 'রিপোর্ট ইমেইল করুন',
    'audit.noSpam': 'বুকিং করে আপনি NextGen Digital Studio এর সাথে যোগাযোগে সম্মত হচ্ছেন।',
    'configurator.eyebrow': 'আপনার স্ট্যাক তৈরি করুন', 'configurator.title1': 'কাস্টম', 'configurator.title2': 'এআই অটোমেশন স্ট্যাক ডিজাইন করুন',
    'configurator.subtitle': 'প্রয়োজনীয় সেবা নির্বাচন করুন এবং মাসিক মূল্য লাইভ দেখুন। ২+ সেবা বান্ডলে স্বয়ংক্রিয় ছাড় — কোনো লুকানো ফি নেই।',
    'configurator.yourStack': 'আপনার স্ট্যাক', 'configurator.reset': 'রিসেট',
    'configurator.monthlyTotal': 'মাসিক মোট', 'configurator.subtotal': 'সাবটোটাল',
    'configurator.youSave': 'আপনি বাঁচান', 'configurator.getThisStack': 'এই স্ট্যাক নিন',
    'configurator.bundleDiscount': 'বান্ডল ছাড় আনলক হয়েছে!',
    'configurator.freeCall': 'ফ্রি স্ট্র্যাটেজি কল · কোনো বাধ্যবাধকতা নেই · যেকোনো সময় বাতিল করুন',
    'configurator.selectServices': 'কাস্টম স্ট্যাক তৈরি করতে সেবা নির্বাচন করুন →',
    'workflow.eyebrow': 'ওয়ার্কফ্লো বিল্ডার', 'workflow.title1': 'আপনার', 'workflow.title2': 'এআই সেলস ফানেল ভিজ্যুয়ালাইজ করুন',
    'workflow.subtitle': 'ধাপগুলো পুনর্বিন্যাস করুন, নতুন যোগ করুন, এবং ফ্লো রান করে দেখুন কিভাবে এআই-চালিত ফানেল ভিজিটরকে বুকড কলে পরিণত করে — স্বয়ংক্রিয়ভাবে।',
    'workflow.yourFunnel': 'আপনার ফানেল', 'workflow.steps': 'ধাপ', 'workflow.reset': 'রিসেট',
    'workflow.runFlow': 'ফ্লো রান করুন', 'workflow.running': 'চলছে...',
    'workflow.addStep': 'ধাপ যোগ করুন', 'workflow.available': 'উপলব্ধ',
    'workflow.emptyFunnel': 'আপনার ফানেল খালি। লাইব্রেরি থেকে ধাপ যোগ করুন →',
    'workflow.addSteps': 'ধাপ যোগ করুন',
    'workflow.funnelProjection': 'ফানেল প্রজেকশন', 'workflow.automationSteps': 'অটোমেশন ধাপ',
    'workflow.alwaysRunning': 'সবসময় চলমান', 'workflow.leadResponse': 'লিড রেসপন্স',
    'workflow.estConversion': 'আনুমানিক কনভার্সন বৃদ্ধি', 'workflow.howThisWorks': 'এই ফানেল কিভাবে কাজ করে',
    'workflow.buildForMe': 'আমার জন্য তৈরি করুন',
    'workflow.step1': 'একজন ভিজিটর আপনার সাইটে আসে',
    'workflow.step2': 'এআই তাৎক্ষণিক বাংলা/ইংরেজিতে সাড়া দেয়',
    'workflow.step3': 'লিড স্বয়ংক্রিয়ভাবে যোগ্য ও ট্যাগড হয়',
    'workflow.step4': 'কল বুক না হওয়া পর্যন্ত ফলো-আপ চলে',
    'videoTest.eyebrow': 'ভিডিও গল্প', 'videoTest.title1': 'সরাসরি শুনুন', 'videoTest.title2': 'আমাদের ক্লায়েন্টদের কাছ থেকে',
    'videoTest.subtitle': 'বাংলাদেশের বাস্তব ব্যবসায়ীরা শেয়ার করছেন কিভাবে NextGen Digital Studio এআই অটোমেশন দিয়ে তাদের বৃদ্ধি রূপান্তর করেছে।',
    'videoTest.becomeNext': 'আমাদের পরবর্তী সাফল্যের গল্প হোন',
    'guarantees.eyebrow': 'আমাদের প্রতিশ্রুতি',
    'pricingFaq.eyebrow': 'প্রাইসিং প্রশ্ন', 'pricingFaq.title1': 'প্রাইসিং সম্পর্কে যা যা', 'pricingFaq.title2': 'জানতে চান',
    'pricingFaq.subtitle': 'এখনও প্রশ্ন আছে? ফ্রি স্ট্র্যাটেজি কল বুক করুন, আমরা সব উত্তর দেব।',
    'pricingFaq.stillHaveQuestions': 'এখনও প্রশ্ন আছে? আমাদের সাথে কথা বলুন',
    'awards.eyebrow': 'পুরস্কার ও স্বীকৃতি', 'awards.title1': 'ফলাফল দেওয়ার জন্য', 'awards.title2': 'স্বীকৃত',
    'awards.subtitle': 'বাংলাদেশের টেক ও বিজনেস কমিউনিটি আমাদের স্বীকৃতি দিয়েছে — এবং আমরা যেসব প্ল্যাটফর্মে কাজ করি সেগুলো আমাদের সার্টিফাই করেছে।',
    'awards.certifiedPartners': 'সার্টিফাইড ও অনুমোদিত পার্টনার',
    'team.meetPeople': 'এআই-এর পেছনের মানুষদের সাথে পরিচিত হোন',
    'team.teamDesc': 'একটি ফোকাসড টিম — কোনো ব্লোট নেই, কোনো হ্যান্ডঅফ নেই, শুধু স্পেশালিস্ট যারা ডেলিভারি করে।',
    'team.workWithUs': 'আমাদের টিমের সাথে কাজ করুন',
    'partner.eyebrow': 'পার্টনার প্রোগ্রাম', 'partner.title1': 'রেফার করুন', 'partner.title2': 'আয় করুন',
    'partner.subtitle': 'বাংলাদেশের ব্যবসাগুলোকে NextGen Digital Studio এ রেফার করে ৪০+ এজেন্সি ও কনসালট্যান্ট রিকারিং কমিশন আয় করছে। যোগ দিন।',
    'partner.commission': 'কমিশন', 'partner.getDashboard': 'আপনার ড্যাশবোর্ড পান',
    'techStack.eyebrow': 'আমাদের টেক স্ট্যাক', 'techStack.title1': 'বিশ্বের সেরা', 'techStack.title2': 'এআই ও অটোমেশন টুল দ্বারা চালিত',
    'techStack.subtitle': 'আমরা এন্টারপ্রাইজ-গ্রেড প্ল্যাটফর্ম ইন্টিগ্রেট করি যা নির্ভরযোগ্য, স্কেলেবল এবং ভবিষ্যত-প্রস্তুত সিস্টেম তৈরি করে।',
    'kb.eyebrow': 'নলেজ বেস', 'kb.title1': 'শিখুন কিভাবে', 'kb.title2': 'আপনার ব্যবসা অটোমেট করবেন',
    'kb.subtitle': 'এআই, অটোমেশন ও গ্রোথের উপর বাস্তবমুখী গাইড, টিউটোরিয়াল ও প্লেবুক — বাংলাদেশের ব্যবসার জন্য লেখা।',
    'kb.searchPlaceholder': 'আর্টিকেল খুঁজুন... (যেমন WhatsApp, CRM, লিড)',
    'kb.bookCall': 'পার্সোনালাইজড অটোমেশন প্ল্যান চান?', 'kb.bookCallLink': 'ফ্রি স্ট্র্যাটেজি কল বুক করুন',
    'freeTools.eyebrow': 'ফ্রি টুল ও রিসোর্স', 'freeTools.title1': 'ফ্রি টুল ডাউনলোড করুন', 'freeTools.title2': 'স্মার্ট অটোমেট করতে',
    'freeTools.subtitle': 'টেমপ্লেট, চেকলিস্ট, ইবুক ও ক্যালকুলেটর — ১২০+ বাংলাদেশি ব্যবসার সাথে পরীক্ষিত। ফ্রি ডাউনলোড।',
    'integrations.eyebrow': 'ইন্টিগ্রেশন ডিরেক্টরি', 'integrations.title1': 'আমরা সংযুক্ত', 'integrations.title2': '২৭+ টুলের সাথে',
    'integrations.title3': 'যা আপনি ব্যবহার করেন',
    'integrations.subtitle': 'আপনার এআই অটোমেশন স্ট্যাক তার ইন্টিগ্রেশনের মতোই ভালো। আমরা আপনার ব্যবসা যেসব প্ল্যাটফর্মে চলে সেগুলোর সাথে সংযুক্ত হই — নিরবচ্ছিন্নভাবে।',
    'integrations.searchPlaceholder': '২৭+ ইন্টিগ্রেশন খুঁজুন...',
    'integrations.dontSeeTool': 'আপনার টুল দেখছেন না?',
    'integrations.dontSeeDesc': 'যেকোনো প্ল্যাটফর্মের জন্য কাস্টম ইন্টিগ্রেশন তৈরি করি যার API আছে।',
    'integrations.requestIntegration': 'ইন্টিগ্রেশন অনুরোধ করুন',
    'careers.eyebrow': 'ক্যারিয়ার', 'careers.title1': 'বাংলাদেশের এআই ভবিষ্যৎ', 'careers.title2': 'তৈরি করুন',
    'careers.subtitle': 'আমরা তীক্ষ্ণ, আবেগী মানুষ খুঁজছি যারা বাংলাদেশের ব্যবসা বাড়াতে বাস্তব এআই প্রোডাক্ট তৈরি করতে চান। যোগ দিন।',
    'careers.openPositions': 'খোলা পদসমূহ', 'careers.dontSeeRole': 'আপনার পদ দেখছেন না?',
    'careers.sendGeneral': 'সাধারণ আবেদন পাঠান',
    'status.eyebrow': 'সিস্টেম স্ট্যাটাস', 'status.title1': 'সব সিস্টেম', 'status.title2': 'চালু',
    'status.subtitle': 'আমরা আমাদের প্ল্যাটফর্ম ২৪/৭ মনিটর করি। এখানে প্রতিটি সেবার রিয়েল-টাইম স্ট্যাটাস।',
    'status.allOperational': 'সব সিস্টেম চালু',
    'status.updatedJustNow': 'এইমাত্র আপডেট হয়েছে · গত ৩০ দিনে ৯৯.৯৬% আপটাইম',
    'status.uptime30day': '৩০-দিনের আপটাইম', 'status.operational': 'চালু',
    'status.recentIncidents': 'সাম্প্রতিক ঘটনা', 'status.haveIssue': 'সমস্যা আছে?',
    'contact.fullName': 'পূর্ণ নাম', 'contact.phone': 'ফোন', 'contact.email': 'ইমেইল',
    'contact.company': 'কোম্পানি', 'contact.serviceInterested': 'কোন সেবায় আগ্রহী',
    'contact.selectService': 'সেবা নির্বাচন করুন', 'contact.message': 'বার্তা',
    'contact.tellAboutProject': 'আপনার প্রজেক্ট ও লক্ষ্য সম্পর্কে বলুন...',
    'contact.sendMessage': 'বার্তা পাঠান', 'contact.sending': 'পাঠানো হচ্ছে...',
    'contact.messageSent': 'বার্তা পাঠানো হয়েছে!',
    'contact.sentDesc': 'যোগাযোগের জন্য ধন্যবাদ। আমাদের টিম ২৪ ঘন্টার মধ্যে উত্তর দেবে।',
    'contact.sendAnother': 'আরেকটি বার্তা পাঠান', 'contact.followWork': 'আমাদের কাজ ফলো করুন',
    // Chat widget UI
    'chat.title': 'NextGen এআই অ্যাসিস্ট্যান্ট',
    'chat.online': '● অনলাইন · তাৎক্ষণিক উত্তর',
    'chat.clearChat': 'চ্যাট মুছুন',
    'chat.bookCall': 'ফ্রি স্ট্র্যাটেজি কল বুক করুন',
    'chat.placeholder': 'আপনার বার্তা লিখুন...',
    'chat.poweredBy': 'NextGen এআই দ্বারা চালিত',
    'chat.callUs': 'কল করুন',
    'chat.urgentEnquiry': 'জরুরি তদন্তের জন্য',
    'chat.suggestion1': 'আপনারা কী কী সেবা দেন?',
    'chat.suggestion2': 'খরচ কত?',
    'chat.suggestion3': 'হোয়াটসঅ্যাপ অটোমেট করতে পারেন?',
    'chat.suggestion4': 'আমি একটি রিয়েল এস্টেট ব্যবসা চালাই',
    'chat.ariaOpen': 'এআই অ্যাসিস্ট্যান্ট চ্যাট খুলুন',
    'chat.ariaClear': 'চ্যাট ইতিহাস মুছুন',
    'chat.ariaClose': 'চ্যাট বন্ধ করুন',
    'chat.ariaSend': 'বার্তা পাঠান',
    // Hero chat demo + floating stats
    'hero.aiAgent': 'এআই সেলস এজেন্ট',
    'hero.onlineBilingual': '● অনলাইন · বাংলা ও ইংরেজি',
    'hero.chatUser1': 'হাই, আমি গুলশানে আপনার ফ্ল্যাটে আগ্রহী। এটা কি পাওয়া যাচ্ছে?',
    'hero.chatUser2': 'হ্যাঁ, শনিবার সকাল ১১টা ঠিক আছে।',
    'hero.chatSuccess': 'সাইট ভিজিট বুকড · লিড যোগ্য · CRM আপডেটেড',
    'hero.qualifiedLeads': 'যোগ্য লিড',
    'hero.responseTime': 'রেসপন্স টাইম',
    'hero.trustedPrefix': 'আস্থা রাখে',
    'hero.businessesCount': '১২০+ ব্যবসা',
  },
}

// Content translation map — English content strings to Bangla
const contentBn: Record<string, string> = {
  // Nav labels
  'About': 'আমাদের সম্পর্কে', 'Services': 'সেবাসমূহ', 'Industries': 'শিল্পখাত',
  'Case Studies': 'কেস স্টাডি', 'Pricing': 'প্রাইসিং', 'Why Us': 'কেন আমরা',
  'Blog': 'ব্লগ', 'Contact': 'যোগাযোগ',
  // Footer column titles
  'Company': 'কোম্পানি',
  // Stats
  'Trusted by 120+ businesses': '১২০+ ব্যবসা আমাদের উপর আস্থা রাখে',
  '120+ client reviews': '১২০+ ক্লায়েন্ট রিভিউ',
  'Founder of NextGen Digital Studio': 'NextGen Digital Studio-এর প্রতিষ্ঠাতা',
  // Services
  'AI Sales Automation': 'এআই সেলস অটোমেশন', 'AI Chat Agent': 'এআই চ্যাট এজেন্ট',
  'AI Voice Agent': 'এআই ভয়েস এজেন্ট', 'CRM Automation': 'CRM অটোমেশন',
  'WhatsApp Automation': 'হোয়াটসঅ্যাপ অটোমেশন', 'Lead Generation': 'লিড জেনারেশন',
  'Performance Marketing': 'পারফরম্যান্স মার্কেটিং', 'Sales Funnel Development': 'সেলস ফানেল ডেভেলপমেন্ট',
  'Business Automation': 'বিজনেস অটোমেশন', 'Website Development': 'ওয়েবসাইট ডেভেলপমেন্ট',
  'Landing Page Design': 'ল্যান্ডিং পেজ ডিজাইন', 'AI Consultation': 'এআই কনসালটেশন',
  'Close more deals with AI-driven outreach, follow-ups & pipeline nurturing.': 'এআই-চালিত আউটরিচ, ফলো-আপ ও পাইপলাইন নার্সিং দিয়ে বেশি ডিল ক্লোজ করুন।',
  'End-to-end AI sales engines that qualify leads, send personalised follow-ups, and hand hot prospects to your team — 24/7.': 'শেষ থেকে শেষ এআই সেলস ইঞ্জিন যা লিড যোগ্যতা যাচাই করে, পার্সোনালাইজড ফলো-আপ পাঠায়, এবং হট প্রসপেক্ট আপনার টিমের কাছে হস্তান্তর করে — ২৪/৭।',
  'A 24/7 AI chatbot trained on your business that converts visitors into leads.': 'আপনার ব্যবসার উপর প্রশিক্ষিত ২৪/৭ এআই চ্যাটবট যা ভিজিটরকে লিডে রূপান্তর করে।',
  'Human-sounding AI voice agents for inbound & outbound calls.': 'ইনবাউন্ড ও আউটবাউন্ড কলের জন্য মানুষের মতো শোনায় এএই এআই ভয়েস এজেন্ট।',
  'Turn your CRM into an autopilot that never drops a lead.': 'আপনার CRM-কে অটোপাইলটে পরিণত করুন যা কখনো লিড হারায় না।',
  "Reach customers on Bangladesh's #1 messaging app — automatically.": 'বাংলাদেশের #১ মেসেজিং অ্যাপে কাস্টমারের কাছে পৌঁছান — স্বয়ংক্রিয়ভাবে।',
  'Predictable, qualified leads on autopilot — every single month.': 'প্রতি মাসে অটোপাইলটে যোগ্য লিড — নিশ্চিত।',
  'Meta, Google & TikTok ads engineered for measurable ROI.': 'মেটা, গুগল ও টিকটক বিজ্ঞাপন — যাচাইযোগ্য ROI-এর জন্য ডিজাইন করা।',
  'High-converting funnels that turn cold traffic into booked calls.': 'হাই-কনভার্টিং ফানেল যা কোল্ড ট্রাফিককে বুকড কলে রূপান্তর করে।',
  'Automate repetitive operations with n8n, Zapier & custom workflows.': 'n8n, Zapier ও কাস্টম ওয়ার্কফ্লো দিয়ে পুনরাবৃত্তিমূলক অপারেশন অটোমেট করুন।',
  'Lightning-fast, SEO-ready websites built on Next.js.': 'Next.js-এ তৈরি দ্রুত, SEO-প্রস্তুত ওয়েবসাইট।',
  'High-converting landing pages built to turn clicks into customers.': 'ক্লিককে কাস্টমারে রূপান্তর করতে তৈরি হাই-কনভার্টিং ল্যান্ডিং পেজ।',
  'A clear AI roadmap to cut costs, scale revenue and automate operations.': 'খরচ কমাতে, রাজস্ব বাড়াতে ও অপারেশন অটোমেট করতে একটি স্পষ্ট এআই রোডম্যাপ।',
  // Problem cards
  'Slow lead response kills deals': 'ধীর লিড রেসপন্স ডিল নষ্ট করে',
  'Repetitive tasks drain your team': 'পুনরাবৃত্তিমূলক কাজ আপনার টিমকে ক্লান্ত করে',
  'Leads slip through the cracks': 'লিড ফসকে যায়',
  "Customers expect instant answers": 'কাস্টমার তাৎক্ষণিক উত্তর প্রত্যাশা করে',
  '78% of customers buy from the company that responds first. Manual replies mean lost revenue — every single hour.': '৭৮% কাস্টমার যিনি প্রথমে সাড়া দেন তার কাছ থেকেই কেনে। ম্যানুয়াল উত্তর মানে হারানো রাজস্ব — প্রতি ঘণ্টায়।',
  'Your staff wastes hours on follow-ups, data entry and FAQs instead of closing deals and serving customers.': 'আপনার স্টাফ ফলো-আপ, ডেটা এন্ট্রি ও FAQ-তে ঘণ্টা নষ্ট করে ডিল ক্লোজ ও কাস্টমার সেবার বদলে।',
  'Without automation, unqualified leads flood your pipeline while hot prospects go cold and untouched.': 'অটোমেশন ছাড়া, অযোগ্য লিড আপনার পাইপলাইনে ভর করে যখন হট প্রসপেক্ট ঠান্ডা ও অস্পর্শিত থেকে যায়।',
  "Today's customers want replies in seconds, not days. Slow communication damages trust and reputation.": 'আজকের কাস্টমার সেকেন্ডে উত্তর চায়, দিনে নয়। ধীর যোগাযোগ বিশ্বাস ও সুনাম নষ্ট করে।',
  // Solution
  'AI Agents that never sleep': 'এআই এজেন্ট যারা কখনো ঘুমায় না',
  'Automation that runs itself': 'অটোমেশন যা নিজে চলে',
  'Omnichannel customer reach': 'সব চ্যানেলে কাস্টমার পৌঁছ',
  'Lead generation on autopilot': 'অটোপাইলটে লিড জেনারেশন',
  'Chat & voice agents trained on your business handle enquiries, qualify leads and book calls 24/7 — in Bangla & English.': 'আপনার ব্যবসার উপর প্রশিক্ষিত চ্যাট ও ভয়েস এজেন্ট যা ২৪/৭ জিজ্ঞাসা সামলায়, লিড যোগ্যতা যাচাই করে ও কল বুক করে — বাংলা ও ইংরেজিতে।',
  'We connect your tools and automate follow-ups, CRM updates, reminders and operations end-to-end with n8n & Zapier.': 'আমরা আপনার টুল সংযুক্ত করি এবং n8n ও Zapier দিয়ে ফলো-আপ, CRM আপডেট, রিমাইন্ডার ও অপারেশন শেষ থেকে শেষ অটোমেট করি।',
  'Website, WhatsApp, SMS, email and voice — all unified into one intelligent system that responds in seconds.': 'ওয়েবসাইট, হোয়াটসঅ্যাপ, SMS, ইমেইল ও ভয়েস — সব একটি বুদ্ধিমান সিস্টেমে একত্রিত যা সেকেন্ডে সাড়া দেয়।',
  'Paid ads, SEO and AI outreach combined into a predictable system that fills your pipeline with qualified leads.': 'পেইড বিজ্ঞাপন, SEO ও এআই আউটরিচ একত্রিত একটি অনুমানযোগ্য সিস্টেমে যা আপনার পাইপলাইন যোগ্য লিড দিয়ে ভরে তোলে।',
  'Everything you need to automate growth — in one place': 'বৃদ্ধি অটোমেট করতে যা যা দরকার — এক জায়গায়',
  'No juggling multiple vendors or tools. We deliver a complete, integrated system tailored to your business goals.': 'একাধিক ভেন্ডর বা টুল নিয়ে ব্যস্ত না হয়ে। আমরা আপনার ব্যবসার লক্ষ্য অনুযায়ী একটি সম্পূর্ণ, ইন্টিগ্রেটেড সিস্টেম ডেলিভারি করি।',
  // Capabilities
  'Instant lead response (under 5 seconds)': 'তাৎক্ষণিক লিড রেসপন্স (৫ সেকেন্ডের কম)',
  'Bilingual Bangla & English AI agents': 'দ্বিভাষিক বাংলা ও ইংরেজি এআই এজেন্ট',
  'Automated WhatsApp & SMS follow-up': 'স্বয়ংক্রিয় হোয়াটসঅ্যাপ ও SMS ফলো-আপ',
  'CRM pipeline automation & tagging': 'CRM পাইপলাইন অটোমেশন ও ট্যাগিং',
  'AI voice agents for calls': 'কলের জন্য এআই ভয়েস এজেন্ট',
  'Full sales funnels that convert': 'কনভার্ট করা সম্পূর্ণ সেলস ফানেল',
  'Performance marketing with clear ROI': 'স্পষ্ট ROI সহ পারফরম্যান্স মার্কেটিং',
  'Business automation that saves 40+ hrs/week': 'বিজনেস অটোমেশন যা সপ্তাহে ৪০+ ঘণ্টা বাঁচায়',
  // Why Choose Us
  "Bangladesh's most results-obsessed AI automation agency": 'বাংলাদেশের সবচেয়ে ফলাফল-আসক্ত এআই অটোমেশন এজেন্সি',
  "We're not just developers — we're growth partners. Every system we build is engineered around one goal: more qualified leads, more booked calls, more revenue.": 'আমরা শুধু ডেভেলপার নই — আমরা গ্রোথ পার্টনার। আমরা যে সিস্টেম তৈরি করি তার একটি লক্ষ্য: বেশি যোগ্য লিড, বেশি বুকড কল, বেশি রাজস্ব।',
  'Bangladesh-First AI': 'বাংলাদেশ-প্রথম এআই', 'Done-For-You System': 'আপনার জন্য তৈরি সিস্টেম',
  'Measurable ROI': 'যাচাইযোগ্য ROI', 'Enterprise-Grade Tech': 'এন্টারপ্রাইজ-গ্রেড প্রযুক্তি',
  'Fast Time-To-Value': 'দ্রুত ফলাফল', 'Local Support Team': 'স্থানীয় সাপোর্ট টিম',
  'Bilingual Bangla & English AI agents built specifically for the local market — not generic global tools.': 'স্থানীয় বাজারের জন্য বিশেষভাবে তৈরি দ্বিভাষিক বাংলা ও ইংরেজি এআই এজেন্ট — সাধারণ গ্লোবাল টুল নয়।',
  'We handle strategy, build, integration and optimisation end-to-end. You focus on closing deals.': 'আমরা কৌশল, বিল্ড, ইন্টিগ্রেশন ও অপ্টিমাইজেশন শেষ থেকে শেষ সামলাই। আপনি ডিল ক্লোজে ফোকাস করুন।',
  'Every automation is tied to revenue. We report on leads, calls and conversions — not vanity metrics.': 'প্রতিটি অটোমেশন রাজস্বের সাথে যুক্ত। আমরা লিড, কল ও কনভার্সন রিপোর্ট করি — অর্থহীন মেট্রিক নয়।',
  'GPT-class models, official WhatsApp API and modern infrastructure trusted by corporates.': 'জিপিটি-শ্রেণীর মডেল, অফিসিয়াল হোয়াটসঅ্যাপ API ও আধুনিক অবকাঠামো যা কর্পোরেটরা বিশ্বাস করে।',
  'Most systems go live in 2–4 weeks. You see qualified leads within the first month.': 'বেশিরভাগ সিস্টেম ২-৪ সপ্তাহে লাইভ হয়। প্রথম মাসেই যোগ্য লিড দেখুন।',
  'A Dhaka-based team that understands your market, your customers and your business culture.': 'ঢাকা-ভিত্তিক একটি টিম যারা আপনার বাজার, কাস্টমার ও ব্যবসায়িক সংস্কৃতি বোঝে।',
  // How It Works
  'Discovery & Audit': 'আবিষ্কার ও অডিট', 'Strategy & Roadmap': 'কৌশল ও রোডম্যাপ',
  'Build & Integrate': 'বিল্ড ও ইন্টিগ্রেট', 'Launch & Optimise': 'লঞ্চ ও অপ্টিমাইজ',
  'We analyse your sales process, customer journey and tools to find the highest-ROI automation opportunities.': 'আমরা আপনার সেলস প্রক্রিয়া, কাস্টমার জার্নি ও টুল বিশ্লেষণ করি সর্বোচ্চ-ROI অটোমেশন সুযোগ খুঁজে বের করতে।',
  'You receive a custom AI + automation roadmap with clear timelines, costs and projected ROI.': 'আপনি একটি কাস্টম এআই + অটোমেশন রোডম্যাপ পান স্পষ্ট টাইমলাইন, খরচ ও প্রজেক্টেড ROI সহ।',
  'We design, build and integrate your AI agents, automations and funnels into your existing stack.': 'আমরা আপনার এআই এজেন্ট, অটোমেশন ও ফানেল ডিজাইন, বিল্ড ও আপনার বিদ্যমান স্ট্যাকে ইন্টিগ্রেট করি।',
  'We go live, monitor performance and continuously optimise to maximise leads, calls and revenue.': 'আমরা লাইভ যাই, পারফরম্যান্স মনিটর করি এবং লিড, কল ও রাজস্ব বাড়াতে ক্রমাগত অপ্টিমাইজ করি।',
  // By The Numbers / Stats
  'AI conversations handled': 'এআই কথোপকথন পরিচালিত', 'Businesses automated': 'ব্যবসা অটোমেটেড',
  'Average client ROI': 'গড় ক্লায়েন্ট ROI', 'Average client rating': 'গড় ক্লায়েন্ট রেটিং',
  'Average cost reduction': 'গড় খরচ হ্রাস', 'Average response time': 'গড় রেসপন্স সময়',
  'Businesses Automated': 'ব্যবসা অটোমেটেড', 'AI Conversations': 'এআই কথোপকথন',
  'Average ROI': 'গড় ROI', 'Avg. Cost Reduction': 'গড় খরচ হ্রাস',
  'Qualified leads': 'যোগ্য লিড', 'Response time': 'রেসপন্স সময়', 'Site visits booked': 'সাইট ভিজিট বুকড',
  // Pricing
  'Starter': 'স্টার্টার', 'Growth': 'গ্রোথ', 'Enterprise': 'এন্টারপ্রাইজ',
  'For small businesses ready to automate.': 'ছোট ব্যবসার জন্য যারা অটোমেট করতে প্রস্তুত।',
  'For scaling companies that need a full system.': 'স্কেলিং কোম্পানির জন্য যাদের সম্পূর্ণ সিস্টেম দরকার।',
  'Custom AI infrastructure for large organisations.': 'বড় প্রতিষ্ঠানের জন্য কাস্টম এআই অবকাঠামো।',
  '1 AI Chat Agent (website)': '১টি এআই চ্যাট এজেন্ট (ওয়েবসাইট)',
  'WhatsApp automation (1 number)': 'হোয়াটসঅ্যাপ অটোমেশন (১ নম্বর)',
  'Lead capture & CRM setup': 'লিড ক্যাপচার ও CRM সেটআপ',
  '2,000 AI conversations/mo': '২,০০০ এআই কথোপকথন/মাস', 'Monthly strategy call': 'মাসিক স্ট্র্যাটেজি কল',
  'Email support': 'ইমেইল সাপোর্ট', 'AI Chat + Voice Agent': 'এআই চ্যাট + ভয়েস এজেন্ট',
  'WhatsApp + SMS automation': 'হোয়াটসঅ্যাপ + SMS অটোমেশন', 'CRM automation (GHL/HubSpot)': 'CRM অটোমেশন (GHL/HubSpot)',
  '10,000 AI conversations/mo': '১০,০০০ এআই কথোপকথন/মাস', 'Landing page + funnel build': 'ল্যান্ডিং পেজ + ফানেল বিল্ড',
  'Performance marketing management': 'পারফরম্যান্স মার্কেটিং ম্যানেজমেন্ট',
  'Weekly strategy calls': 'সাপ্তাহিক স্ট্র্যাটেজি কল', 'Priority support': 'অগ্রাধিকার সাপোর্ট',
  'Unlimited AI agents & channels': 'আনলিমিটেড এআই এজেন্ট ও চ্যানেল',
  'Custom AI model training': 'কাস্টম এআই মডেল ট্রেইনিং', 'Full business automation suite': 'সম্পূর্ণ বিজনেস অটোমেশন স্যুট',
  'Dedicated automation engineer': 'ডেডিকেটেড অটোমেশন ইঞ্জিনিয়ার', 'API & system integrations': 'API ও সিস্টেম ইন্টিগ্রেশন',
  'Unlimited strategy sessions': 'আনলিমিটেড স্ট্র্যাটেজি সেশন', 'SLA & 24/7 support': 'SLA ও ২৪/৭ সাপোর্ট',
  'White-label options': 'হোয়াইট-লেবেল অপশন', '/month': '/মাস', '/mo': '/মাস', 'Custom': 'কাস্টম',
  'Most Popular': 'সবচেয়ে জনপ্রিয়', 'Need something custom?': 'কাস্টম কিছু দরকার?',
  // Guarantees
  '30-Day ROI Promise': '৩০-দিনের ROI প্রতিশ্রুতি', 'No Long Lock-in': 'কোনো দীর্ঘ চুক্তি নেই',
  'Bank-grade Security': 'ব্যাংক-গ্রেড নিরাপত্তা', 'Dhaka-based Support': 'ঢাকা-ভিত্তিক সাপোর্ট',
  'See qualified leads in the first month or we work free until you do.': 'প্রথম মাসে যোগ্য লিড দেখুন বা আমরা ফ্রিতে কাজ করব।',
  'Monthly plans. Cancel anytime — no multi-year contracts holding you hostage.': 'মাসিক প্ল্যান। যেকোনো সময় বাতিল করুন — কোনো বহু-বছরের চুক্তি নেই।',
  'Your data is encrypted, never sold. Official APIs only — no shady shortcuts.': 'আপনার ডেটা এনক্রিপ্টেড, কখনো বিক্রি হয় না। শুধু অফিসিয়াল API — কোনো অবৈধ শর্টকাট নেই।',
  'A local team that understands your market and responds in Bangla.': 'স্থানীয় একটি টিম যারা আপনার বাজার বোঝে এবং বাংলায় সাড়া দেয়।',
  // Comparison
  'AI chat agent on your website': 'ওয়েবসাইটে এআই চ্যাট এজেন্ট', 'Lead response time': 'লিড রেসপন্স সময়',
  '24/7, trained on your business, Bangla + English': '২৪/৭, আপনার ব্যবসায় প্রশিক্ষিত, বাংলা + ইংরেজি',
  'Generic chatbot or none': 'সাধারণ চ্যাটবট বা নেই', 'Under 5 seconds, fully automated': '৫ সেকেন্ডের কম, সম্পূর্ণ স্বয়ংক্রিয়',
  'Hours or days, manual': 'ঘণ্টা বা দিন, ম্যানুয়াল', 'Full pipeline auto-nurture & tagging': 'সম্পূর্ণ পাইপলাইন অটো-নার্সার ও ট্যাগিং',
  'Basic setup or manual data entry': 'সাধারণ সেটআপ বা ম্যানুয়াল ডেটা এন্ট্রি',
  'Official API, broadcasts, chatbots': 'অফিসিয়াল API, ব্রডকাস্ট, চ্যাটবট', 'Personal WhatsApp or none': 'ব্যক্তিগত হোয়াটসঅ্যাপ বা নেই',
  'Native Bangla + English switching': 'নেটিভ বাংলা + ইংরেজি সুইচিং', 'English-only or template messages': 'শুধু ইংরেজি বা টেমপ্লেট মেসেজ',
  'Clear monthly plans from ৳25,000': '৳২৫,০০০ থেকে স্পষ্ট মাসিক প্ল্যান', 'Opaque quotes, hidden fees': 'অস্বচ্ছ কোট, লুকানো ফি',
  'Dhaka-based, understands local market': 'ঢাকা-ভিত্তিক, স্থানীয় বাজার বোঝে', 'Overseas or generic agency': 'বিদেশি বা সাধারণ এজেন্সি',
  'Leads, calls & revenue tracked': 'লিড, কল ও রাজস্ব ট্র্যাকড', 'Vanity metrics or nothing': 'অর্থহীন মেট্রিক বা কিছু না',
  'Feature': 'ফিচার', 'Typical Agencies': 'সাধারণ এজেন্সি', '& freelancers': 'ও ফ্রিল্যান্সার',
  // Testimonials
  'Founder': 'প্রতিষ্ঠাতা', 'Director': 'পরিচালক', 'CEO': 'সিইও', 'Marketing Head': 'মার্কেটিং প্রধান',
  'Dhaka Realty Group': 'ঢাকা রিয়েলটি গ্রুপ', 'Medicare Hospital': 'মেডিকেয়ার হাসপাতাল',
  'ShopSmart BD': 'শপস্মার্ট বিডি', 'EduFirst School Network': 'এডুফার্স্ট স্কুল নেটওয়ার্ক',
  // Industries
  'Small & Medium Businesses': 'ছোট ও মাঝারি ব্যবসা', 'Corporate Companies': 'কর্পোরেট কোম্পানি',
  'Real Estate': 'রিয়েল এস্টেট', 'Hospitals & Clinics': 'হাসপাতাল ও ক্লিনিক',
  'Schools & Education': 'স্কুল ও শিক্ষা', 'E-commerce': 'ই-কমার্স', 'Agencies': 'এজেন্সি',
  'Manufacturing': 'ম্যানুফ্যাকচারিং',
  // AI Demo
  'Trained on your business — answers questions like your best salesperson': 'আপনার ব্যবসায় প্রশিক্ষিত — আপনার সেরা সেলসপারসনের মতো প্রশ্নের উত্তর দেয়',
  'Bilingual: switches between Bangla and English mid-conversation': 'দ্বিভাষিক: কথোপকথনে বাংলা ও ইংরেজির মধ্যে সুইচ করে',
  'Captures leads, books calls and routes to your team automatically': 'লিড ক্যাপচার করে, কল বুক করে এবং স্বয়ংক্রিয়ভাবে আপনার টিমে রুট করে',
  'Site visit booked · Lead qualified · CRM updated': 'সাইট ভিজিট বুকড · লিড যোগ্য · CRM আপডেটেড',
  // Hero chat demo
  'AI Sales Agent': 'এআই সেলস এজেন্ট',
  'Online · Bangla & English': 'অনলাইন · বাংলা ও ইংরেজি',
  "Hi, I'm interested in your apartment in Gulshan. Is it available?": 'হাই, আমি আপনার গুলশানের ফ্ল্যাটে আগ্রহী। এটা কি পাওয়া যাচ্ছে?',
  'আসসালামু আলাইকুম! Yes, the 3-bed Gulshan apartment is available. Would you like to book a site visit this weekend? 🏠': 'আসসালামু আলাইকুম! হ্যাঁ, গুলশানের ৩-বেড ফ্ল্যাটটি পাওয়া যাচ্ছে। আপনি কি এই সপ্তাহান্তে সাইট ভিজিট বুক করতে চান? 🏠',
  'Yes please, Saturday 11am works.': 'হ্যাঁ, শনিবার সকাল ১১টা ঠিক আছে।',
  // AI Demo chat messages
  "Hi, I'm interested in your Gulshan apartment. Is the 3-bed available?": 'হাই, গুলশানের ফ্ল্যাটে আগ্রহী। ৩-বেড কি পাওয়া যাচ্ছে?',
  'আসসালামু আলাইকুম! Yes, the 3-bed on level 6 is available. It has 2,150 sqft with a premium view. Would you like to book a site visit this Saturday at 11am?': 'আসসালামু আলাইকুম! হ্যাঁ, ৬ষ্ঠ তলার ৩-বেড পাওয়া যাচ্ছে। ২,১৫০ স্কয়ার ফুট, প্রিমিয়াম ভিউ। শনিবার সকাল ১১টায় সাইট ভিজিট বুক করবেন?',
  "Saturday 11am works. What's the price?": 'শনিবার ১১টা ঠিক আছে। দাম কত?',
  "Great, site visit booked for Saturday 11am ✓. The price is ৳1.85 crore (negotiable). I'll send full details and the location pin to your WhatsApp. What's your number?": 'দারুণ, শনিবার ১১টার জন্য সাইট ভিজিট বুকড ✓। দাম ৳১.৮৫ কোটি (আলোচনাসাপেক্ষে)। আমি বিস্তারিত ও লোকেশন পিন আপনার হোয়াটসঅ্যাপে পাঠাব। আপনার নম্বর কত?',
  // Team section
  'AI Engineer': 'এআই ইঞ্জিনিয়ার',
  'Growth Specialist': 'গ্রোথ স্পেশালিস্ট',
  'Automation Architect': 'অটোমেশন আর্কিটেক্ট',
  'LLM & Automation': 'LLM ও অটোমেশন',
  'CRM & Integrations': 'CRM ও ইন্টিগ্রেশন',
  'Builds GPT-class chat agents, voice agents and n8n workflows that run 24/7 without human intervention.': 'GPT-শ্রেণীর চ্যাট এজেন্ট, ভয়েস এজেন্ট ও n8n ওয়ার্কফ্লো তৈরি করে যা ২৪/৭ মানুষের হস্তক্ষেপ ছাড়াই চলে।',
  'Manages Meta, Google & TikTok ad funnels engineered for qualified leads — not just clicks.': 'মেটা, গুগল ও টিকটক বিজ্ঞাপন ফানেল পরিচালনা করে যা যোগ্য লিডের জন্য ডিজাইন করা — শুধু ক্লিকের জন্য নয়।',
  'Designs GoHighLevel, HubSpot & WhatsApp API flows that never drop a lead across the entire journey.': 'GoHighLevel, HubSpot ও WhatsApp API ফ্লো ডিজাইন করে যা সম্পূর্ণ যাত্রায় কখনো লিড হারায় না।',
  'Mission': 'মিশন',
  'Vision': 'ভিশন',
  'Values': 'ভ্যালুস',
  'To make enterprise-grade AI accessible to every Bangladeshi business — so they can compete and win in the AI era.': 'প্রতিটি বাংলাদেশি ব্যবসার কাছে এন্টারপ্রাইজ-গ্রেড এআই পৌঁছে দেওয়া — যাতে তারা এআই যুগে প্রতিযোগিতা করে জিততে পারে।',
  'A Bangladesh where small businesses automate like global tech companies — faster, smarter, and 24/7.': 'এমন একটি বাংলাদেশ যেখানে ছোট ব্যবসাগুলো গ্লোবাল টেক কোম্পানির মতো অটোমেট করে — দ্রুত, স্মার্ট, এবং ২৪/৭।',
  'Radical transparency, measurable ROI, bilingual-first design, and genuine partnership over vendor relationships.': 'চরম স্বচ্ছতা, যাচাইযোগ্য ROI, দ্বিভাষিক-প্রথম ডিজাইন, এবং ভেন্ডার সম্পর্কের চেয়ে সত্যিকারের অংশীদারিত্ব।',
  'Meet the people behind the AI': 'এআই-এর পেছনের মানুষদের সাথে পরিচিত হোন',
  'A focused team — no bloat, no handoffs, just specialists who ship.': 'একটি ফোকাসড টিম — কোনো ব্লোট নেই, কোনো হ্যান্ডঅফ নেই, শুধু স্পেশালিস্ট যারা ডেলিভারি করে।',
  // Partner program
  'Referrer': 'রেফারার',
  'Partner': 'পার্টনার',
  'Strategic': 'স্ট্র্যাটেজিক',
  'Refer a client, earn 10% recurring commission for 12 months.': 'একজন ক্লায়েন্ট রেফার করুন, ১২ মাসের জন্য ১০% রিকারিং কমিশন আয় করুন।',
  'For agencies reselling our AI services under white-label.': 'যেসব এজেন্সি আমাদের এআই সেবা হোয়াইট-লেবেলে পুনরায় বিক্রি করে।',
  'For large networks & consultatives moving high volume.': 'বড় নেটওয়ার্ক ও কনসালট্যান্টদের জন্য যারা বেশি ভলিউম নিয়ে কাজ করে।',
  'Personal referral link': 'ব্যক্তিগত রেফারাল লিংক',
  'Monthly payouts': 'মাসিক পেমেন্ট',
  'Dashboard access': 'ড্যাশবোর্ড অ্যাক্সেস',
  'White-label AI agents': 'হোয়াইট-লেবেল এআই এজেন্ট',
  'Co-marketing kit': 'কো-মার্কেটিং কিট',
  'Dedicated manager': 'ডেডিকেটেড ম্যানেজার',
  'Custom revenue share': 'কাস্টম রাজস্ব ভাগ',
  'Joint ventures': 'যৌথ উদ্যোগ',
  'Exclusive territory': 'এক্সক্লুসিভ এলাকা',
  'Quarterly strategy': 'ত্রৈমাসিক কৌশল',
  'Already referring? Track your earnings in real-time.': 'ইতিমধ্যে রেফার করছেন? আপনার আয় রিয়েল-টাইমে ট্র্যাক করুন।',
  // Awards
  'Top AI Agency 2024': 'শীর্ষ এআই এজেন্সি ২০২৪',
  'Best Automation Studio': 'সেরা অটোমেশন স্টুডিও',
  'Fastest Growing Tech Co.': 'দ্রুততম বর্ধনশীল টেক কোম্পানি',
  'Innovation Excellence': 'ইনোভেশন এক্সিলেন্স',
  'Bangladesh Tech Awards': 'বাংলাদেশ টেক অ্যাওয়ার্ডস',
  'Dhaka Business Review': 'ঢাকা বিজনেস রিভিউ',
  'Startup BD': 'স্টার্টআপ বিডি',
  'ICT Division Bangladesh': 'আইসিটি বিভাগ বাংলাদেশ',
  // Certifications
  'WhatsApp Business Partner': 'হোয়াটসঅ্যাপ বিজনেস পার্টনার',
  'Official API access': 'অফিসিয়াল API অ্যাক্সেস',
  'Meta Business Partner': 'মেটা বিজনেস পার্টনার',
  'Certified ads management': 'সার্টিফাইড বিজ্ঞাপন ব্যবস্থাপনা',
  'Google Partner': 'গুগল পার্টনার',
  'Premier ads & analytics': 'প্রিমিয়ার বিজ্ঞাপন ও অ্যানালিটিক্স',
  'GoHighLevel Pro': 'GoHighLevel প্রো',
  'Certified SaaS automation': 'সার্টিফাইড SaaS অটোমেশন',
  'HubSpot Solutions': 'HubSpot সলিউশনস',
  'Certified CRM partner': 'সার্টিফাইড CRM পার্টনার',
  'OpenAI API': 'OpenAI API',
  'Authorized integration': 'অনুমোদিত ইন্টিগ্রেশন',
  // Careers
  'Cutting-edge AI': 'অত্যাধুনিক এআই',
  'Fast growth': 'দ্রুত বৃদ্ধি',
  'Real impact': 'প্রকৃত প্রভাব',
  'Great team': 'দুর্দান্ত টিম',
  'Work with GPT-4, voice agents & automation daily': 'প্রতিদিন GPT-4, ভয়েস এজেন্ট ও অটোমেশন নিয়ে কাজ করুন',
  'We are scaling fast — grow your career with us': 'আমরা দ্রুত বাড়ছি — আপনার ক্যারিয়ার বাড়ান আমাদের সাথে',
  'Your work directly grows 120+ Bangladeshi businesses': 'আপনার কাজ সরাসরি ১২০+ বাংলাদেশি ব্যবসা বাড়ায়',
  'Small, sharp, no-ego team that ships fast': 'ছোট, তীক্ষ্ণ, অহংকারহীন টিম যারা দ্রুত ডেলিভারি করে',
  // Status page
  'Website & Landing Pages': 'ওয়েবসাইট ও ল্যান্ডিং পেজ',
  'CRM & Lead Pipeline': 'CRM ও লিড পাইপলাইন',
  'API & Webhooks': 'API ও ওয়েবহুক',
  'Email & Notifications': 'ইমেইল ও নোটিফিকেশন',
  'AI Chat Agent latency spike': 'এআই চ্যাট এজেন্ট লেটেন্সি বৃদ্ধি',
  'Brief 3-minute latency increase due to upstream LLM provider maintenance. Resolved automatically.': 'আপস্ট্রিম LLM প্রোভাইডার মেইনটেন্যান্সের কারণে সংক্ষিপ্ত ৩-মিনিট লেটেন্সি বৃদ্ধি। স্বয়ংক্রিয়ভাবে সমাধান হয়েছে।',
  'Scheduled database maintenance': 'নির্ধারিত ডেটাবেস মেইনটেন্যান্স',
  '15-minute planned maintenance for database optimization. No data loss. Completed ahead of schedule.': 'ডেটাবেস অপ্টিমাইজেশনের জন্য ১৫-মিনিটের পরিকল্পিত মেইনটেন্যান্স। কোনো ডেটা লস নেই। নির্ধারিত সময়ের আগেই সম্পন্ন।',
  'resolved': 'সমাধান হয়েছে',
  // FAQ
  'Still have questions?': 'এখনও প্রশ্ন আছে?',
  'Get a free 30-min consultation.': 'ফ্রি ৩০-মিনিট কনসালটেশন পান।',
  // Footer industries
  'Hospitals': 'হাসপাতাল',
  'Schools': 'স্কুল',
  'Corporate': 'কর্পোরেট',
  // ROI Calculator
  'Lead response Improvement': 'লিড রেসপন্স উন্নতি',
  'Hours Saved Per Week': 'সাপ্তাহিক সাশ্রয়িত সময়',
  'Faster AI response typically converts 20–200% more leads': 'দ্রুত এআই রেসপন্স সাধারণত ২০-২০০% বেশি লিড কনভার্ট করে',
  'Time freed from manual follow-ups, data entry & support': 'ম্যানুয়াল ফলো-আপ, ডেটা এন্ট্রি ও সাপোর্ট থেকে মুক্ত সময়',
  'Estimates based on industry benchmarks from our 120+ client deployments across Bangladesh. Actual results vary.': 'বাংলাদেশে আমাদের ১২০+ ক্লায়েন্ট ডিপ্লয়মেন্ট থেকে ইন্ডাস্ট্রি বেঞ্চমার্কের উপর ভিত্তি করে অনুমান। প্রকৃত ফলাফল ভিন্ন হতে পারে।',
  'YOUR PROJECTED YEARLY IMPACT': 'আপনার প্রজেক্টেড বার্ষিক প্রভাব',
  'Total value created per year': 'বার্ষিক মোট মূল্য',
  'Extra qualified leads / mo': 'অতিরিক্ত যোগ্য লিড / মাস',
  'Revenue uplift / year': 'রাজস্ব বৃদ্ধি / বছর',
  'Hours saved / year': 'সাশ্রয়িত সময় / বছর',
  'Labour cost saved': 'শ্রম খরচ সাশ্রয়',
  'Estimated ROI multiple': 'আনুমানিক ROI মাল্টিপল',
  'Get my detailed ROI breakdown': 'বিস্তারিত ROI ব্রেকডাউন পান',
  // Comparison ROI
  'See qualified leads in your first month — or we keep working free until you do.': 'প্রথম মাসে যোগ্য লিড দেখুন — নাহলে আমরা ফ্রিতে কাজ চালিয়ে যাব।',
  'Start risk-free': 'ঝুঁকিমুক্ত শুরু করুন',
  // Configurator items
  'WhatsApp Bot': 'হোয়াটসঅ্যাপ বট',
  '24/7 website chatbot trained on your business': 'আপনার ব্যবসায় প্রশিক্ষিত ২৪/৭ ওয়েবসাইট চ্যাটবট',
  'Bilingual voice agent for inbound & outbound calls': 'ইনবাউন্ড ও আউটবাউন্ড কলের জন্য দ্বিভাষিক ভয়েস এজেন্ট',
  'Official WhatsApp Business API chatbot & broadcasts': 'অফিসিয়াল WhatsApp Business API চ্যাটবট ও ব্রডকাস্ট',
  'GoHighLevel/HubSpot pipeline & follow-up automation': 'GoHighLevel/HubSpot পাইপলাইন ও ফলো-আপ অটোমেশন',
  'Multi-channel lead gen with AI outreach': 'এআই আউটরিচ সহ মাল্টি-চ্যানেল লিড জেনারেশন',
  'Landing page + email/SMS sequence build': 'ল্যান্ডিং পেজ + ইমেইল/SMS সিকোয়েন্স বিল্ড',
  'Meta & Google Ads management + creatives': 'মেটা ও গুগল বিজ্ঞাপন ব্যবস্থাপনা + ক্রিয়েটিভ',
  'Premium Next.js website with SEO': 'প্রিমিয়াম Next.js ওয়েবসাইট SEO সহ',
  'High-converting standalone landing page': 'হাই-কনভার্টিং স্ট্যান্ডঅ্যালোন ল্যান্ডিং পেজ',
  'Strategy session + custom AI roadmap': 'কৌশল সেশন + কাস্টম এআই রোডম্যাপ',
  // Workflow steps
  'Landing Page': 'ল্যান্ডিং পেজ',
  'Visitor lands on your optimized page': 'ভিজিটর আপনার অপ্টিমাইজড পেজে আসে',
  'AI Chat': 'এআই চ্যাট',
  'AI engages & qualifies the lead': 'এআই সাড়া দেয় ও লিড যোগ্যতা যাচাই করে',
  'WhatsApp Follow-up': 'হোয়াটসঅ্যাপ ফলো-আপ',
  'Instant WhatsApp message sent': 'তাৎক্ষণিক হোয়াটসঅ্যাপ মেসেজ পাঠানো হয়',
  'CRM Auto-Tag': 'CRM অটো-ট্যাগ',
  'Lead tagged & added to pipeline': 'লিড ট্যাগড ও পাইপলাইনে যোগ হয়',
  'Email Sequence': 'ইমেইল সিকোয়েন্স',
  '3-day nurture email flow': '৩-দিনের নার্সার ইমেইল ফ্লো',
  'AI Voice Call': 'এআই ভয়েস কল',
  'AI books a strategy call': 'এআই একটি স্ট্র্যাটেজি কল বুক করে',
  'Booked Meeting': 'বুকড মিটিং',
  'Calendar invite sent automatically': 'ক্যালেন্ডার ইনভাইট স্বয়ংক্রিয়ভাবে পাঠানো হয়',
  'Revenue Tracking': 'রাজস্ব ট্র্যাকিং',
  'Conversion tracked in dashboard': 'কনভার্সন ড্যাশবোর্ডে ট্র্যাক করা হয়',
  // Blog posts
  'How AI Sales Automation is Reshaping Bangladeshi SMEs in 2025': 'কিভাবে এআই সেলস অটোমেশন ২০২৫ সালে বাংলাদেশি এসএমই-কে বদলে দিচ্ছে',
  'The Complete WhatsApp Business API Guide for Bangladeshi E-commerce': 'বাংলাদেশি ই-কমার্সের জন্য সম্পূর্ণ WhatsApp Business API গাইড',
  'Why Hospitals in Bangladesh Are Switching to AI Voice Agents': 'কেন বাংলাদেশের হাসপাতালগুলো এআই ভয়েস এজেন্টে চলে যাচ্ছে',
  'The CRM Automation Playbook: Never Drop a Lead Again': 'CRM অটোমেশন প্লেবুক: আর কখনো লিড হারাবেন না',
  '7 min read': '৭ মিনিট পড়ুন',
  '9 min read': '৯ মিনিট পড়ুন',
  '6 min read': '৬ মিনিট পড়ুন',
  '8 min read': '৮ মিনিট পড়ুন',
  // Knowledge base / Free tools / Integrations categories
  'AI Automation': 'এআই অটোমেশন',
  'AI Voice': 'এআই ভয়েস',
  'Automation': 'অটোমেশন',
  'AI & LLM': 'এআই ও LLM',
  'Messaging': 'মেসেজিং',
  'Marketing': 'মার্কেটিং',
  'Analytics': 'অ্যানালিটিক্স',
  'Web': 'ওয়েব',
  'All': 'সব',
  // Configurator categories
  'AI Agents': 'এআই এজেন্ট',
  // Misc
  'Bangladesh': 'বাংলাদেশ',
  // Chat widget greeting + error (stored in state, translated at render via tr())
  "Assalamu Alaikum! 👋 I'm the NextGen AI Assistant. I can answer questions about our AI automation services, pricing, and how we can grow your business. How can I help you today?": 'আসসালামু আলাইকুম! 👋 আমি NextGen এআই অ্যাসিস্ট্যান্ট। আমাদের এআই অটোমেশন সেবা, প্রাইসিং এবং কিভাবে আমরা আপনার ব্যবসা বাড়াতে পারি তা নিয়ে প্রশ্নের উত্তর দিতে পারি। আজ আমি কিভাবে সাহায্য করতে পারি?',
  "I'm having trouble connecting right now. Please book a free strategy call and our team will help you directly. 🙂": 'এই মুহূর্তে সংযোগে সমস্যা হচ্ছে। একটি ফ্রি স্ট্র্যাটেজি কল বুক করুন, আমাদের টিম সরাসরি সাহায্য করবে। 🙂',
}

function tr(en: string, lang: Lang): string {
  if (lang === 'en') return en
  return contentBn[en] ?? en
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = React.useState<Lang>('en')
  const [mounted, setMounted] = React.useState(false)

  React.useEffect(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY) as Lang | null
      if (saved === 'en' || saved === 'bn') setLangState(saved)
    } catch {}
    setMounted(true)
  }, [])

  const setLang = React.useCallback((l: Lang) => {
    setLangState(l)
    try { localStorage.setItem(STORAGE_KEY, l) } catch {}
    document.documentElement.lang = l
  }, [])

  const toggle = React.useCallback(() => {
    setLang(lang === 'en' ? 'bn' : 'en')
  }, [lang, setLang])

  const t = React.useCallback((key: string) => {
    return translations[lang][key] ?? translations.en[key] ?? key
  }, [lang])

  const trFn = React.useCallback((en: string) => {
    return tr(en, lang)
  }, [lang])

  const value = React.useMemo(() => ({ lang, setLang, toggle, t, tr: trFn }), [lang, setLang, toggle, t, trFn])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLang() {
  const ctx = React.useContext(LanguageContext)
  if (!ctx) throw new Error('useLang must be used within LanguageProvider')
  return ctx
}
